import type { ToggleSwitchDesignTokens } from '@primeuix/themes/types/toggleswitch';

export const toggleswitch: ToggleSwitchDesignTokens = {
  root: {
    width: '2.5rem',
    height: '1.5rem',
    borderRadius: '30px',
    gap: '0.25rem',
    focusRing: {
      width: '{focus.ring.width}',
      style: '{focus.ring.style}',
      offset: '{focus.ring.offset}',
    },
    borderWidth: '1px',
    borderColor: 'transparent',
    hoverBorderColor: 'transparent',
    checkedBorderColor: 'transparent',
    checkedHoverBorderColor: 'transparent',
    invalidBorderColor: '{form.field.invalid.border.color}',
    transitionDuration: '{form.field.transition.duration}',
    slideDuration: '0.2s',
  },
  handle: {
    borderRadius: '50%',
    size: '1rem',
  },
  colorScheme: {
    light: {
      root: {
        background: '{surface.700}',
        disabledBackground: '{form.field.disabled.background}',
        hoverBackground: '{primary.400}',
        checkedBackground: '{surface.700}',
        checkedHoverBackground: '{primary.400}',
        borderColor: 'transparent',
        hoverBorderColor: 'transparent',
        checkedBorderColor: 'transparent',
        checkedHoverBorderColor: 'transparent',
        invalidBorderColor: '{form.field.invalid.border.color}',
        shadow: '{form.field.shadow}',
        focusRing: {
          color: '{focus.ring.color}',
          shadow: '{focus.ring.shadow}',
        },
      },
      handle: {
        background: '{surface.500}',
        disabledBackground: '{form.field.disabled.color}',
        hoverBackground: '{surface.800}',
        checkedBackground: '{primary.500}',
        checkedHoverBackground: '{surface.800}',
        color: '{red.500}',
        hoverColor: '{red.500}',
        checkedColor: '{red.500}',
        checkedHoverColor: '{red.500}',
      },
    },
    dark: {
      root: {
        background: '{surface.700}',
        disabledBackground: '{form.field.disabled.background}',
        hoverBackground: '{primary.400}',
        checkedBackground: '{surface.700}',
        checkedHoverBackground: '{primary.hover.color}',
        borderColor: 'transparent',
        hoverBorderColor: 'transparent',
        checkedBorderColor: 'transparent',
        checkedHoverBorderColor: 'transparent',
        invalidBorderColor: '{form.field.invalid.border.color}',
        shadow: '{form.field.shadow}',
        focusRing: {
          color: '{focus.ring.color}',
          shadow: '{focus.ring.shadow}',
        },
      },
      handle: {
        background: '{surface.400}',
        disabledBackground: '{surface.900}',
        hoverBackground: '{surface.300}',
        checkedBackground: '{surface.900}',
        checkedHoverBackground: '{surface.900}',
        color: '{surface.900}',
        hoverColor: '{surface.800}',
        checkedColor: '{primary.color}',
        checkedHoverColor: '{primary.hover.color}',
      },
    },
  },
};
