export const semantic = {
  transitionDuration: '0.2s',
  focusRing: {
    width: '1px',
    style: 'solid',
    offset: '2px',
    shadow: 'none',
  },
  disabledOpacity: '0.6',
  iconSize: '1rem',
  anchorGutter: '2px',
  primary: {
    50: '{blue.50}',
    100: '{blue.100}',
    200: '{blue.200}',
    300: '{blue.300}',
    400: '{blue.400}',
    500: '{blue.500}',
    600: '{blue.600}',
    700: '{blue.700}',
    800: '{blue.800}',
    900: '{blue.900}',
    950: '{blue.950}',
  },

  formField: {
    paddingX: '0.75rem',
    paddingY: '0.5rem',
    sm: {
      fontSize: '0.875rem',
      paddingX: '0.625rem',
      paddingY: '0.375rem',
    },
    lg: {
      fontSize: '1.125rem',
      paddingX: '0.875rem',
      paddingY: '0.625rem',
    },
    borderRadius: '{border.radius.md}',
    focusRing: {
      width: '0',
      style: 'none',
      color: 'transparent',
      offset: '0',
      shadow: 'none',
    },
    transitionDuration: '{transition.duration}',
  },
  list: {
    padding: '0.25rem 0.25rem',
    gap: '2px',
    header: {
      padding: '0.5rem 1rem 0.25rem 1rem',
    },
    option: {
      padding: '0.5rem 0.75rem',
      borderRadius: '{border.radius.sm}',
    },
    optionGroup: {
      padding: '0.5rem 0.75rem',
      fontWeight: '600',
    },
  },
  content: {
    borderRadius: '{border.radius.md}',
  },
  mask: {
    transitionDuration: '0.3s',
  },
  navigation: {
    list: {
      padding: '0.25rem 0.25rem',
      gap: '2px',
    },
    item: {
      padding: '0.5rem 0.75rem',
      borderRadius: '{border.radius.sm}',
      gap: '0.5rem',
    },
    submenuLabel: {
      padding: '0.5rem 0.75rem',
      fontWeight: '600',
    },
    submenuIcon: {
      size: '0.875rem',
    },
  },
  overlay: {
    select: {
      borderRadius: '{border.radius.md}',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
    popover: {
      borderRadius: '{border.radius.md}',
      padding: '0.75rem',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
    modal: {
      borderRadius: '{border.radius.xl}',
      padding: '1.25rem',
      shadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
    },
    navigation: {
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
  },
  colorScheme: {
    light: {
      surface: {
        0: '#000000',
        50: '{gray.950}',
        100: '{gray.900}',
        200: '{gray.800}',
        300: '{gray.700}',
        400: '{gray.600}',
        500: '{gray.500}',
        600: '{gray.400}',
        700: '{gray.300}',
        800: '{gray.200}',
        900: '{gray.100}',
        950: '{gray.50}',
      },
      primary: {
        color: '{primary.500}',
        contrastColor: '#ffffff',
        hoverColor: '{primary.600}',
        activeColor: '{primary.700}',
      },
      highlight: {
        background: '{primary.50}',
        focusBackground: '{primary.100}',
        color: '{primary.700}',
        focusColor: '{primary.800}',
      },
      content: {
        background: '{surface.900}',
        borderColor: '{surface.700}',
        color: '{text.color}',
        hoverBackground: '{surface.800}',
        hoverColor: '{text.hover.color}',
      },
      formField: {
        background: '{surface.900}',
        borderColor: '{surface.500}',
        color: '{surface.500}',
        disabledBackground: '{surface.700}',
        disabledColor: '{surface.400}',
        filledBackground: '{surface.800}',
        filledFocusBackground: '{surface.800}',
        filledHoverBackground: '{surface.800}',
        floatLabelActiveColor: '{surface.400}',
        floatLabelColor: '{surface.400}',
        floatLabelFocusColor: '{primary.color}',
        floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
        focusBorderColor: '{primary.color}',
        hoverBorderColor: '{surface.500}',
        iconColor: '{surface.400}',
        invalidBorderColor: '{red.300}',
        invalidPlaceholderColor: '{red.400}',
        placeholderColor: '{surface.400}',
        shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
      },
    },
    dark: {
      surface: {
        0: '#ffffff',
        50: '{gray.50}',
        100: '{gray.100}',
        200: '{gray.200}',
        300: '{gray.300}',
        400: '{gray.400}',
        500: '{gray.500}',
        600: '{gray.600}',
        700: '{gray.700}',
        800: '{gray.800}',
        900: '{gray.900}',
        950: '{gray.950}',
      },
      primary: {
        activeColor: '{red.500}',
        color: '{blue.500}',
        contrastColor: '{surface.100}',
        hoverColor: '{blue.600}',
      },
      secondary: {
        activeColor: '{green.500}',
        color: '{blue.500}',
        contrastColor: '{surface.100}',
        hoverColor: '{blue.600}',
      },
      content: {
        background: '{surface.900}',
        borderColor: '{surface.700}',
        color: '{text.color}',
        hoverBackground: '{surface.800}',
        hoverColor: '{text.hover.color}',
      },
      formField: {
        background: '{surface.900}',
        borderColor: '{surface.500}',
        color: '{surface.0}',
        disabledBackground: '{surface.700}',
        disabledColor: '{surface.400}',
        filledBackground: '{surface.800}',
        filledFocusBackground: '{surface.800}',
        filledHoverBackground: '{surface.800}',
        floatLabelActiveColor: '{surface.400}',
        floatLabelColor: '{surface.400}',
        floatLabelFocusColor: '{primary.color}',
        floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
        focusBorderColor: '{primary.color}',
        hoverBorderColor: '{surface.500}',
        iconColor: '{surface.400}',
        invalidBorderColor: '{red.300}',
        invalidPlaceholderColor: '{red.400}',
        placeholderColor: '{surface.400}',
        shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
      },
      highlight: {
        background: '{red.500}',
        color: '{red.500}',
        focusBackground: '{red.500}',
        focusColor: '{red.500}',
      },
      list: {
        option: {
          color: '{text.color}',
          focusBackground: '{surface.800}',
          focusColor: '{text.hover.color}',
          selectedBackground: '{highlight.background}',
          selectedColor: '{highlight.color}',
          selectedFocusBackground: '{highlight.focus.background}',
          selectedFocusColor: '{highlight.focus.color}',
          icon: {
            color: '{surface.500}',
            focusColor: '{surface.400}',
          },
        },
        optionGroup: {
          background: 'transparent',
          color: '{text.muted.color}',
        },
      },
      mask: {
        background: 'rgba(0,0,0,0.6)',
        color: '{surface.200}',
      },
      navigation: {
        item: {
          activeBackground: '{surface.800}',
          activeColor: '{text.hover.color}',
          color: '{text.color}',
          focusBackground: '{surface.800}',
          focusColor: '{text.hover.color}',
          icon: {
            color: '{surface.500}',
            focusColor: '{surface.400}',
            activeColor: '{surface.400}',
          },
        },
        submenuIcon: {
          activeColor: '{surface.400}',
          color: '{surface.500}',
          focusColor: '{surface.400}',
        },
        submenuLabel: {
          background: 'transparent',
          color: '{text.muted.color}',
        },
      },
      overlay: {
        select: {
          background: '{surface.700}',
          borderColor: '{surface.400}',
          color: '{text.color}',
        },
        popover: {
          background: '{surface.900}',
          borderColor: '{surface.700}',
          color: '{text.color}',
        },
        modal: {
          background: '{surface.900}',
          borderColor: '{surface.700}',
          color: '{text.color}',
        },
      },
      text: {
        color: '{surface.0}',
        hoverColor: '{surface.0}',
        hoverMutedColor: '{surface.300}',
        mutedColor: '{surface.400}',
      },
    },
  },
};
