import type { SelectDesignTokens } from '@primeuix/themes/types/select';

export const select: SelectDesignTokens = {
  root: {
    background: '{form.field.background}',
    disabledBackground: '{form.field.disabled.background}',
    filledBackground: '{form.field.filled.background}',
    filledHoverBackground: '{form.field.filled.hover.background}',
    filledFocusBackground: '{form.field.filled.focus.background}',
    borderColor: '{form.field.border.color}',
    hoverBorderColor: '{form.field.hover.border.color}',
    focusBorderColor: '{form.field.focus.border.color}',
    invalidBorderColor: '{form.field.invalid.border.color}',
    color: '{surface.200}',
    disabledColor: '{form.field.disabled.color}',
    placeholderColor: '{form.field.placeholder.color}',
    invalidPlaceholderColor: '{form.field.invalid.placeholder.color}',
    shadow: '{form.field.shadow}',
    paddingX: '{form.field.padding.x}',
    paddingY: '{form.field.padding.y}',
    borderRadius: '{form.field.border.radius}',
    focusRing: {
      width: '{form.field.focus.ring.width}',
      style: '{form.field.focus.ring.style}',
      color: '{form.field.focus.ring.color}',
      offset: '{form.field.focus.ring.offset}',
      shadow: '{form.field.focus.ring.shadow}',
    },
    transitionDuration: '{form.field.transition.duration}',
    sm: {
      fontSize: '{form.field.sm.font.size}',
      paddingX: '{form.field.sm.padding.x}',
      paddingY: '{form.field.sm.padding.y}',
    },
    lg: {
      fontSize: '{form.field.lg.font.size}',
      paddingX: '{form.field.lg.padding.x}',
      paddingY: '{form.field.lg.padding.y}',
    },
  },
  option: {},
  checkmark: {},
  clearIcon: {},
  dropdown: {},
  emptyMessage: {},
  list: {},
  optionGroup: {},
  overlay: {
    background: '{overlay.select.background}',
    borderColor: '{overlay.select.border.color}',
    borderRadius: '{overlay.select.border.radius}',
    color: '{overlay.select.color}',
    shadow: '{overlay.select.shadow}',
  },
  colorScheme: {
    light: {
      root: {},
      option: {
        focusBackground: '{primary.400}',
        selectedBackground: '{primary.100}',
        selectedFocusBackground: '{primary.400}',
        color: '{surface.100}',
        focusColor: '{surface.900}',
        selectedColor: '{surface.100}',
        selectedFocusColor: '{surface.900}',
      },
      checkmark: {},
      clearIcon: {},
      dropdown: {},
      emptyMessage: {},
      list: {},
      optionGroup: {},
      overlay: {
        background: '{surface.800}',
        borderColor: '{surface.600}',
        color: '{surface.100}',
        shadow: '{overlay.select.shadow}',
      },
    },
    dark: {
      root: {
        color: '{red.50}',
      },
      option: {
        focusBackground: '{surface.500}',
        selectedBackground: '{surface.400}',
        selectedFocusBackground: '{surface.400}',
        color: '{red.50}',
        focusColor: '{red.50}',
        selectedColor: '{red.50}',
        selectedFocusColor: '{red.50}',
      },
    },
  },
};
