pub mod inference;
pub mod models;
mod queue;
pub mod db;
mod settings;
mod utils;
mod claude;
mod chatbot;
mod logging;
pub mod vision;
pub mod server;
pub mod shared;
pub mod client;
mod batch;

pub use logging::init_logging;

use tauri::{command, Manager, Emitter};
use std::sync::Arc;
use tauri::State;
use tokio::sync::Mutex;
use tracing::{warn, info};
use queue::QueueProcessor;
use db::InferenceDb;

#[derive(Clone)]
pub struct AppState {
    pub inference_db: Arc<Mutex<Option<db::InferenceDb>>>,
    pub queue_manager: Arc<queue::QueueManager>,
    pub queue_processor: Arc<QueueProcessor>,
    pub model_config_cache: Arc<models::ModelConfigCache>,
    pub app_handle: tauri::AppHandle,
    pub download_in_progress: Arc<Mutex<bool>>,
    pub runtime_config: shared::protocol::RuntimeConfig,
    /// WebSocket state for server mode (None in local/client mode)
    pub ws_state: Option<Arc<server::ws_state::WsState>>,
    /// Client API client for client mode (None in local/server mode)
    pub client_api: Option<Arc<client::api::ApiClient>>,
}

#[command]
fn health_check() -> String {
    "OK".to_string()
}

#[command]
async fn init_database(app_state: State<'_, AppState>, db_path: String) -> Result<String, String> {
    // Create parent directory if it doesn't exist
    if let Some(parent) = std::path::Path::new(&db_path).parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create database directory: {}", e))?;
    }

    let db = db::InferenceDb::new(&db_path)
        .map_err(|e| format!("Failed to open database: {}", e))?;

    db.init_schema()
        .map_err(|e| format!("Failed to initialize schema: {}", e))?;


    *app_state.inference_db.lock().await = Some(db);

    // Load model configs into cache
    app_state.model_config_cache.load_all().await
        .map_err(|e| format!("Failed to load model configs: {}", e))?;

    Ok("Database initialized".to_string())
}

/// Generate an image from a text prompt using Flux model
///
/// # Arguments
/// * `prompt` - Text description of image to generate
/// * `steps` - Number of diffusion steps
/// * `width` - Image width in pixels
/// * `height` - Image height in pixels
/// * `seed` - Random seed for generation (-1 for random)
///
/// # Returns
/// File path to the generated image
#[command]
async fn generate_image(
    app_state: State<'_, AppState>,
    prompt: String,
    steps: u32,
    width: u32,
    height: u32,
    seed: i64,
) -> Result<String, String> {
    use crate::inference::{InferenceEngine, FluxPipeline};
    use crate::db::ImageMetadata;
    use std::fs;

    // Get or create inference engine
    let engine = InferenceEngine::new()
        .map_err(|e| format!("Failed to initialize inference engine: {}", e))?;

    let device = engine.get_device().clone();
    let mut pipeline = FluxPipeline::new(device)
        .map_err(|e| format!("Failed to create pipeline: {}", e))?;

    // Generate image using FLUX
    // Convert seed to u64 (negative means use random)
    let seed_u64 = if seed >= 0 { seed as u64 } else { rand::random::<u64>() };
    let result = pipeline.generate(
        &prompt,
        steps as usize,
        width as usize,
        height as usize,
        4.0, // Default guidance for FLUX Schnell
        seed_u64,
        inference::SamplerType::default(),
        inference::SchedulerType::default(),
    ).map_err(|e| format!("Generation failed: {}", e))?;

    // Determine output path
    let home = dirs::home_dir()
        .ok_or_else(|| "Could not determine home directory".to_string())?;
    let output_dir = home.join(".rzem-ai-inference").join("outputs");

    // Create output directory
    fs::create_dir_all(&output_dir)
        .map_err(|e| format!("Failed to create output directory: {}", e))?;

    // Generate filename with timestamp
    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|e| format!("System time error: {}", e))?
        .as_secs();
    let filename = format!("flux_{}_{}.png", timestamp, seed);
    let output_path = output_dir.join(&filename);

    // Save PNG image data
    fs::write(&output_path, &result.image_data)
        .map_err(|e| format!("Failed to write image: {}", e))?;

    // Insert into gallery database
    let db = app_state.inference_db.lock().await;
    if let Some(db) = db.as_ref() {
        let image_id = uuid::Uuid::new_v4().to_string();

        // Calculate file size
        let file_size = std::fs::metadata(&output_path)
            .map(|m| m.len() as i64)
            .unwrap_or(0);

        let metadata = ImageMetadata {
            id: image_id.clone(),
            file_path: Some(output_path.to_string_lossy().to_string()),
            thumbnail_path: None, // Thumbnails are generated by the queue processor
            prompt: prompt.clone(),
            created_at: timestamp as i64,
            width: Some(width as i32),
            height: Some(height as i32),
            file_size: Some(file_size),
            model_name: "flux-schnell".to_string(),
            negative_prompt: None,
            steps: Some(steps as i32),
            cfg_scale: Some(4.0), // Hardcoded guidance for FLUX Schnell
            seed: Some(seed),
            sampler: Some(format!("{:?}", inference::SamplerType::default())),
            generation_time_ms: Some(result.stats.total_ms as i64),
            status: "completed".to_string(),
            session_id: None,
            updated_at: timestamp as i64,
            loras: None,  // No LoRAs in test command
        };
        if let Err(e) = db.insert_image(&metadata) {
            warn!(error = %e, "Failed to insert image into gallery");
        }
        // Store generation stats
        if let Err(e) = db.insert_generation_stats(&image_id, &result.stats) {
            warn!(error = %e, "Failed to insert generation stats");
        }
    }

    Ok(output_path.to_string_lossy().to_string())
}

#[command]
async fn get_gallery_images(
    app_state: State<'_, AppState>,
    limit: usize,
) -> Result<Vec<db::GalleryImage>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    // Get all COMPLETED images regardless of session (for gallery view)
    db.get_images_by_status("completed", limit as i64)
        .map_err(|e| format!("Failed to get images: {}", e))
}

#[command]
async fn get_queue_images(
    app_state: State<'_, AppState>,
    limit: Option<i64>,
) -> Result<Vec<db::GalleryImage>, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref().ok_or("Database not initialized")?;

    // Get current session ID
    let session_id = db.get_setting("current_session_id")
        .ok()
        .flatten()
        .ok_or("Session ID not set")?;

    // Get pending images for current session
    db.get_images_by_session_status(&session_id, "pending", limit.unwrap_or(100))
        .map_err(|e| format!("Failed to get queue images: {}", e))
}

#[command]
async fn get_history_images(
    app_state: State<'_, AppState>,
    limit: Option<i64>,
) -> Result<Vec<db::GalleryImage>, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref().ok_or("Database not initialized")?;

    // Get current session ID
    let session_id = db.get_setting("current_session_id")
        .ok()
        .flatten()
        .ok_or("Session ID not set")?;

    // Get completed images for current session
    db.get_images_by_session_status(&session_id, "completed", limit.unwrap_or(100))
        .map_err(|e| format!("Failed to get history images: {}", e))
}

#[command]
async fn search_gallery_images(
    app_state: State<'_, AppState>,
    query: String,
) -> Result<Vec<db::ImageMetadata>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.search_gallery_images(&query)
        .map_err(|e| format!("Failed to search images: {}", e))
}

#[command]
async fn toggle_favorite(
    app_state: State<'_, AppState>,
    image_id: String,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.toggle_favorite(&image_id)
        .map_err(|e| format!("Failed to toggle favorite: {}", e))?;

    Ok("Favorite toggled".to_string())
}

#[command]
async fn add_image_tag(
    app_state: State<'_, AppState>,
    image_id: String,
    tag: String,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.add_image_tag(&image_id, &tag)
        .map_err(|e| format!("Failed to add tag: {}", e))?;

    Ok("Tag added".to_string())
}

#[command]
async fn remove_image_tag(
    app_state: State<'_, AppState>,
    image_id: String,
    tag: String,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.remove_image_tag(&image_id, &tag)
        .map_err(|e| format!("Failed to remove tag: {}", e))?;

    Ok("Tag removed".to_string())
}

#[command]
async fn delete_gallery_image(
    app_state: State<'_, AppState>,
    image_id: String,
) -> Result<String, String> {
    let db = app_state
        .inference_db
        .lock()
        .await;

    let db = db.as_ref().ok_or("Database not initialized")?;

    // Get image metadata
    let image = db.get_image_by_id(&image_id)
        .map_err(|e| format!("Failed to get image: {}", e))?
        .ok_or_else(|| "Image not found".to_string())?;

    // Delete file from filesystem (proceed even if file is missing)
    if let Some(file_path) = &image.file_path {
        if let Err(e) = std::fs::remove_file(file_path) {
            if e.kind() != std::io::ErrorKind::NotFound {
                return Err(format!("Failed to delete file: {}", e));
            }
            // File already gone - continue with database cleanup
        }
    }

    // Delete from database (this will cascade to image_tags)
    db.delete_gallery_image(&image_id)
        .map_err(|e| format!("Failed to delete from database: {}", e))?;

    Ok("Image deleted".to_string())
}

// ========== Folder Commands ==========

#[command]
async fn create_folder(
    app_state: State<'_, AppState>,
    name: String,
    parent_id: Option<String>,
    color: Option<String>,
    icon: Option<String>,
) -> Result<db::Folder, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.create_folder(&name, parent_id.as_deref(), color.as_deref(), icon.as_deref())
        .map_err(|e| format!("Failed to create folder: {}", e))
}

#[command]
async fn update_folder(
    app_state: State<'_, AppState>,
    id: String,
    name: Option<String>,
    color: Option<String>,
    icon: Option<String>,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.update_folder(&id, name.as_deref(), color.as_deref(), icon.as_deref())
        .map_err(|e| format!("Failed to update folder: {}", e))?;

    Ok("Folder updated".to_string())
}

#[command]
async fn delete_folder(
    app_state: State<'_, AppState>,
    id: String,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.delete_folder(&id)
        .map_err(|e| format!("Failed to delete folder: {}", e))?;

    Ok("Folder deleted".to_string())
}

#[command]
async fn move_folder(
    app_state: State<'_, AppState>,
    id: String,
    new_parent_id: Option<String>,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.move_folder(&id, new_parent_id.as_deref())
        .map_err(|e| format!("Failed to move folder: {}", e))?;

    Ok("Folder moved".to_string())
}

#[command]
async fn get_folder_tree(
    app_state: State<'_, AppState>,
) -> Result<Vec<db::FolderNode>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_folder_tree()
        .map_err(|e| format!("Failed to get folder tree: {}", e))
}

#[command]
async fn add_images_to_folder(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    folder_id: String,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.add_images_to_folder(&image_ids, &folder_id)
        .map_err(|e| format!("Failed to add images to folder: {}", e))?;

    Ok("Images added to folder".to_string())
}

#[command]
async fn remove_images_from_folder(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    folder_id: String,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.remove_images_from_folder(&image_ids, &folder_id)
        .map_err(|e| format!("Failed to remove images from folder: {}", e))?;

    Ok("Images removed from folder".to_string())
}

#[command]
async fn get_folder_images(
    app_state: State<'_, AppState>,
    folder_id: String,
    include_descendants: bool,
    limit: usize,
) -> Result<Vec<db::GalleryImage>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_folder_images(&folder_id, include_descendants, limit)
        .map_err(|e| format!("Failed to get folder images: {}", e))
}

#[command]
async fn get_uncategorized_images(
    app_state: State<'_, AppState>,
    limit: usize,
) -> Result<Vec<db::GalleryImage>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_uncategorized_images(limit)
        .map_err(|e| format!("Failed to get uncategorized images: {}", e))
}

// ========== Enhanced Tag Commands ==========

#[command]
async fn get_all_tags(
    app_state: State<'_, AppState>,
) -> Result<Vec<db::Tag>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_all_tags()
        .map_err(|e| format!("Failed to get tags: {}", e))
}

#[command]
async fn update_tag(
    app_state: State<'_, AppState>,
    id: i64,
    name: Option<String>,
    color: Option<String>,
    category: Option<String>,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.update_tag(id, name.as_deref(), color.as_deref(), category.as_deref())
        .map_err(|e| format!("Failed to update tag: {}", e))?;

    Ok("Tag updated".to_string())
}

#[command]
async fn bulk_add_tag(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    tag: String,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.bulk_add_tag(&image_ids, &tag)
        .map_err(|e| format!("Failed to bulk add tag: {}", e))?;

    Ok("Tag added to images".to_string())
}

#[command]
async fn bulk_remove_tag(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    tag: String,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.bulk_remove_tag(&image_ids, &tag)
        .map_err(|e| format!("Failed to bulk remove tag: {}", e))?;

    Ok("Tag removed from images".to_string())
}

#[command]
async fn delete_tag(
    app_state: State<'_, AppState>,
    tag_id: i64,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.delete_tag(tag_id)
        .map_err(|e| format!("Failed to delete tag: {}", e))?;

    Ok("Tag deleted".to_string())
}

#[command]
async fn reorder_folders(
    app_state: State<'_, AppState>,
    folder_ids: Vec<String>,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.reorder_folders(&folder_ids)
        .map_err(|e| format!("Failed to reorder folders: {}", e))?;

    Ok("Folders reordered".to_string())
}

#[command]
async fn add_to_queue(
    app_state: State<'_, AppState>,
    params: queue::GenerationParams,
) -> Result<String, String> {
    // Generate image ID upfront
    let image_id = uuid::Uuid::new_v4().to_string();

    // Get current session ID from settings
    let session_id = {
        let db_guard = app_state.inference_db.lock().await;
        if let Some(db) = db_guard.as_ref() {
            db.get_setting("current_session_id")
                .ok()
                .flatten()
                .unwrap_or_else(|| uuid::Uuid::new_v4().to_string())
        } else {
            uuid::Uuid::new_v4().to_string()
        }
    };

    // Create pending image entry BEFORE queueing job
    {
        let db_guard = app_state.inference_db.lock().await;
        if let Some(db) = db_guard.as_ref() {
            db.create_pending_image(&image_id, &params, &session_id)
                .map_err(|e| format!("Failed to create pending image: {}", e))?;
        }
    }

    // Queue the job with the pre-generated image_id
    let job_id = app_state.queue_manager.add_job_with_image_id(params, image_id.clone()).await;

    // Emit event for new job (both Tauri and WebSocket)
    emit_job_update(&app_state, &job_id, "pending", 0.0, None, None).await;

    Ok(job_id)
}

#[command]
async fn get_queue_jobs(
    app_state: State<'_, AppState>,
) -> Result<Vec<queue::GenerationJob>, String> {
    let jobs = app_state.queue_manager.get_jobs().await;
    Ok(jobs)
}

#[command]
async fn get_queue_job(
    app_state: State<'_, AppState>,
    job_id: String,
) -> Result<Option<queue::GenerationJob>, String> {
    let job = app_state.queue_manager.get_job(&job_id).await;
    Ok(job)
}

#[command]
async fn cancel_queue_job(
    app_state: State<'_, AppState>,
    job_id: String,
) -> Result<bool, String> {
    let cancelled = app_state.queue_manager.cancel_job(&job_id).await;

    if cancelled {
        // Emit event for cancelled job (both Tauri and WebSocket)
        emit_job_update(&app_state, &job_id, "cancelled", 0.0, None, None).await;
    }

    Ok(cancelled)
}

#[command]
async fn clear_completed_jobs(
    app_state: State<'_, AppState>,
) -> Result<(), String> {
    app_state.queue_manager.clear_completed().await;
    Ok(())
}

#[command]
async fn download_flux_schnell(app_state: State<'_, AppState>) -> Result<String, String> {
    use crate::models::ModelDownloader;

    // Check if download is already in progress
    {
        let mut in_progress = app_state.download_in_progress.lock().await;
        if *in_progress {
            return Err("Download already in progress".to_string());
        }
        *in_progress = true;
    }

    // Ensure we reset the flag even on error
    let result = async {
        let downloader = ModelDownloader::new()
            .map_err(|e| e.to_string())?;

        if downloader.is_schnell_downloaded() {
            return Ok("FLUX Schnell is already downloaded".to_string());
        }

        downloader.download_schnell()
            .await
            .map_err(|e| e.to_string())?;

        Ok("FLUX Schnell downloaded successfully".to_string())
    }.await;

    // Reset the flag
    *app_state.download_in_progress.lock().await = false;

    result
}

#[command]
async fn download_flux_dev(app_state: State<'_, AppState>) -> Result<String, String> {
    use crate::models::ModelDownloader;

    // Check if download is already in progress
    {
        let mut in_progress = app_state.download_in_progress.lock().await;
        if *in_progress {
            return Err("Download already in progress".to_string());
        }
        *in_progress = true;
    }

    // Ensure we reset the flag even on error
    let result = async {
        let downloader = ModelDownloader::new()
            .map_err(|e| e.to_string())?;

        if downloader.is_dev_downloaded() {
            return Ok("FLUX Dev is already downloaded".to_string());
        }

        downloader.download_dev()
            .await
            .map_err(|e| e.to_string())?;

        Ok("FLUX Dev downloaded successfully".to_string())
    }.await;

    // Reset the flag
    *app_state.download_in_progress.lock().await = false;

    result
}

#[command]
fn check_models_downloaded() -> Result<bool, String> {
    use crate::models::ModelDownloader;

    let downloader = ModelDownloader::new()
        .map_err(|e| e.to_string())?;

    Ok(downloader.is_schnell_downloaded())
}

#[derive(serde::Serialize)]
struct ModelAvailability {
    id: String,
    name: String,
    is_downloaded: bool,
    has_quantized: bool,
}

/// Scan HuggingFace cache for available models (transformers only)
#[command]
fn scan_models() -> Result<Vec<models::DiscoveredComponent>, String> {
    let all_components = models::scan_all_components()
        .map_err(|e| format!("Failed to scan models: {}", e))?;

    // Filter to transformers only for this command
    let transformers = all_components
        .into_iter()
        .filter(|c| c.component_type == models::ComponentType::Transformer)
        .collect();

    Ok(transformers)
}

/// Get availability status of all supported models
#[command]
async fn get_available_models(
    app_state: State<'_, AppState>,
) -> Result<Vec<ModelAvailability>, String> {
    use crate::models::ModelPaths;

    // Use shared database from AppState
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;

    let paths = ModelPaths::new(db)
        .map_err(|e| e.to_string())?;

    let bundle_id = paths.bundle_id()
        .unwrap_or("unknown")
        .to_string();

    Ok(vec![
        ModelAvailability {
            id: bundle_id.clone(),
            name: format!("FLUX Bundle: {}", bundle_id),
            is_downloaded: paths.all_files_exist(),
            has_quantized: false, // Quantization is now handled at component level
        },
    ])
}

#[derive(serde::Serialize)]
struct ModelFileStatus {
    name: String,
    exists: bool,
    path: String,
}

#[command]
async fn get_model_status(
    app_state: State<'_, AppState>,
) -> Result<Vec<ModelFileStatus>, String> {
    use crate::models::ModelPaths;

    // Use shared database from AppState
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;

    let paths = ModelPaths::new(db)
        .map_err(|e| e.to_string())?;

    let status = paths.get_status()
        .into_iter()
        .map(|(name, exists, path)| ModelFileStatus { name, exists, path })
        .collect();

    Ok(status)
}

/// Structured component availability for UI display
#[derive(serde::Serialize)]
struct ComponentAvailability {
    id: String,
    name: String,
    description: String,
    is_downloaded: bool,
    size_estimate: String,
    has_quantized: bool,
    quantized_downloaded: bool,
}

/// Get availability status of model components (VAE, CLIP, T5)
#[command]
async fn get_component_availability(
    app_state: State<'_, AppState>,
) -> Result<Vec<ComponentAvailability>, String> {
    use crate::models::ModelPaths;

    // Use shared database from AppState
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;

    let paths = ModelPaths::new(db)
        .map_err(|e| e.to_string())?;

    // Check each component's availability in the bundle
    let clip_downloaded = paths.clip_path()
        .map(|p| p.exists())
        .unwrap_or(false);

    let vae_downloaded = paths.vae_path()
        .map(|p| p.exists())
        .unwrap_or(false);

    let t5_downloaded = paths.t5_path()
        .map(|p| p.exists())
        .unwrap_or(false);

    let t5_tokenizer_downloaded = paths.t5_tokenizer_path()
        .map(|p| p.exists())
        .unwrap_or(false);

    Ok(vec![
        ComponentAvailability {
            id: "vae".to_string(),
            name: "FLUX VAE".to_string(),
            description: "Variational Autoencoder for encoding images to latent space and decoding back".to_string(),
            is_downloaded: vae_downloaded,
            size_estimate: "~335 MB".to_string(),
            has_quantized: false,
            quantized_downloaded: false,
        },
        ComponentAvailability {
            id: "clip".to_string(),
            name: "CLIP Text Encoder".to_string(),
            description: "OpenAI CLIP model for encoding text prompts into embeddings".to_string(),
            is_downloaded: clip_downloaded,
            size_estimate: "~250 MB".to_string(),
            has_quantized: false,
            quantized_downloaded: false,
        },
        ComponentAvailability {
            id: "t5".to_string(),
            name: "T5-XXL Text Encoder".to_string(),
            description: "Google T5-XXL encoder for detailed text understanding and long prompts".to_string(),
            is_downloaded: t5_downloaded,
            size_estimate: "~9 GB".to_string(),
            has_quantized: false,
            quantized_downloaded: false,
        },
        ComponentAvailability {
            id: "t5-tokenizer".to_string(),
            name: "T5 Tokenizer".to_string(),
            description: "Tokenizer for converting text to tokens for T5 encoder".to_string(),
            is_downloaded: t5_tokenizer_downloaded,
            size_estimate: "~2 MB".to_string(),
            has_quantized: false,
            quantized_downloaded: false,
        },
    ])
}


// ========== Model Bundle System Commands ==========

#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct ScanResult {
    components_found: usize,
    components_added: usize,
    bundles_created: usize,
}

/// Scan HuggingFace cache and discover all model components and bundles
#[command]
async fn scan_and_discover_models(
    app_state: State<'_, AppState>,
) -> Result<ScanResult, String> {
    use crate::models::{scan_all_components_with_callbacks, BundleBuilder, to_component_record};
    use tracing::{info, error};
    use std::sync::{Arc, Mutex as StdMutex};

    // Skip scan in dev mode if SKIP_SCAN_IN_DEV is set
    // if cfg!(debug_assertions) && std::env::var("SKIP_SCAN_IN_DEV").is_ok() {
    //     info!("⏭️  Skipping model scan (dev mode + SKIP_SCAN_IN_DEV set)");
    //     return Ok(ScanResult {
    //         components_found: 0,
    //         components_added: 0,
    //         bundles_created: 0,
    //     });
    // }

    info!("🔄 ========================================");
    info!("🔄 scan_and_discover_models COMMAND CALLED");
    info!("🔄 ========================================");
    info!("🔄 Starting model scan and discovery process");

    // Emit scan start event
    let _ = app_state.app_handle.emit("model-scan-progress", serde_json::json!({
        "stage": "scanning",
        "message": "Initializing scan...",
        "progress": 0
    }));

    // Shared counters for tracking progress across callbacks
    let total_components = Arc::new(StdMutex::new(0usize));
    let new_components_count = Arc::new(StdMutex::new(0usize));
    let new_bundles_count = Arc::new(StdMutex::new(0usize));

    // Create progress callback to emit UI events
    let app_handle = app_state.app_handle.clone();
    let progress_callback = Box::new(move |current: usize, total: usize, repo_name: &str| {
        info!("📡 Emitting scan progress: [{}/{}] {}", current, total, repo_name);
        let _ = app_handle.emit("model-scan-progress", serde_json::json!({
            "stage": "scanning",
            "message": format!("[{}/{}] Scanning: {}", current, total, repo_name),
            "progress": (current * 100 / total.max(1)) as u8
        }));
    });

    // Create hash progress callback for detailed hash updates
    let app_handle2 = app_state.app_handle.clone();
    let hash_progress_callback = Box::new(move |filename: &str, percent: u8, processed: u64, total: u64| {
        let processed_gb = processed as f64 / 1_000_000_000.0;
        let total_gb = total as f64 / 1_000_000_000.0;
        let _ = app_handle2.emit("model-scan-progress", serde_json::json!({
            "stage": "hashing",
            "message": format!("Computing hash for {} ({}% - {:.1}/{:.1} GB)", filename, percent, processed_gb, total_gb),
            "progress": percent
        }));
    });

    // Create repo skip callback - checks if repo+snapshot already exists in DB
    let db_arc2 = app_state.inference_db.clone();
    let repo_skip_callback = Box::new(move |repo_id: &str, snapshot_hash: &str| -> bool {
        // Get database access
        let db_guard = tokio::runtime::Handle::current().block_on(async {
            db_arc2.lock().await
        });

        let db = match db_guard.as_ref() {
            Some(d) => d,
            None => return false, // If DB not available, don't skip
        };

        // Check if this repo+snapshot has already been scanned
        match db.has_repo_snapshot(repo_id, snapshot_hash) {
            Ok(exists) => {
                if exists {
                    info!("   ✓ Repo {} with snapshot {} already scanned, skipping", repo_id, &snapshot_hash[..8]);
                }
                exists
            }
            Err(e) => {
                warn!("   ⚠ Failed to check repo snapshot: {} - will scan", e);
                false // On error, don't skip
            }
        }
    });

    // Create repo completion callback - called after each repo is scanned
    let db_arc = app_state.inference_db.clone();
    let app_handle3 = app_state.app_handle.clone();
    let total_components_clone = total_components.clone();
    let new_components_clone = new_components_count.clone();
    let new_bundles_clone = new_bundles_count.clone();

    let repo_completion_callback = Box::new(move |repo_name: &str, repo_components: Vec<models::DiscoveredComponent>| {
        let repo_components = models::filter_sharded_components(repo_components);
        info!("🎁 Processing repo: {} with {} components", repo_name, repo_components.len());

        // Update total component count
        {
            let mut total = total_components_clone.lock().unwrap();
            *total += repo_components.len();
        }

        // Emit progress: processing repo
        let _ = app_handle3.emit("model-scan-progress", serde_json::json!({
            "stage": "processing",
            "message": format!("Processing repo: {}", repo_name),
            "progress": 50
        }));

        // Get database access (blocking on async mutex in sync context)
        let db_guard = tokio::runtime::Handle::current().block_on(async {
            db_arc.lock().await
        });

        let db = match db_guard.as_ref() {
            Some(d) => d,
            None => {
                error!("❌ Database not initialized for repo {}", repo_name);
                return;
            }
        };

        // Insert components from this repo
        let mut repo_new_components = 0;
        for comp in &repo_components {
            let record = to_component_record(comp);
            match db.insert_component(&record) {
                Ok(_) => {
                    info!("   ✓ Added component: {} ({})", record.name, record.component_type);
                    repo_new_components += 1;
                }
                Err(e) => {
                    info!("   ⚠ Component exists: {} - {}", record.name, e);
                }
            }
        }

        // Update new components counter
        {
            let mut new_count = new_components_clone.lock().unwrap();
            *new_count += repo_new_components;
        }

        // Create bundles from this repo's components
        info!("   🎁 Creating bundles for repo: {}", repo_name);
        let builder = BundleBuilder::new(repo_components);
        let bundles = builder.auto_create_bundles();

        if !bundles.is_empty() {
            info!("      Found {} potential bundle(s)", bundles.len());
        }

        let mut repo_new_bundles = 0;
        for bundle_def in &bundles {
            // Calculate total VRAM
            let total_vram: i32 = bundle_def.component_map.iter()
                .filter_map(|(_, comp_id)| {
                    db.get_component(comp_id).ok()
                        .and_then(|c| c.vram_mb)
                })
                .sum();

            let is_complete = bundle_def.component_map.len() >= 4; // transformer + t5 + clip + vae
            let bundle_record = bundle_def.to_record(total_vram, is_complete);

            match db.insert_bundle(&bundle_record) {
                Ok(_) => {
                    // Add component relationships
                    for (role, comp_id) in &bundle_def.component_map {
                        let _ = db.add_component_to_bundle(&bundle_record.id, comp_id, role, true, 0);
                    }

                    let completeness = if is_complete { "complete" } else { "incomplete" };
                    let vram_gb = total_vram as f32 / 1000.0;
                    info!("      ✓ Created bundle: {} ({}, ~{:.1} GB VRAM)",
                        bundle_def.name, completeness, vram_gb);

                    repo_new_bundles += 1;
                }
                Err(_) => {
                    // Bundle already exists, skip silently
                }
            }
        }

        // Update new bundles counter
        if repo_new_bundles > 0 {
            let mut new_count = new_bundles_clone.lock().unwrap();
            *new_count += repo_new_bundles;
            info!("   ✓ Created {} bundle(s) for repo {}", repo_new_bundles, repo_name);
        }
    });

    // Run scanner with all callbacks in a blocking task
    // (scanner is sync and uses block_on in callbacks, so it must run in spawn_blocking)
    info!("📡 About to call scanner...");
    let components = tokio::task::spawn_blocking(move || {
        scan_all_components_with_callbacks(
            Some(progress_callback),
            Some(hash_progress_callback),
            Some(repo_completion_callback),
            Some(repo_skip_callback)
        )
    })
    .await
    .map_err(|e| format!("Scanner task panicked: {}", e))?
    .map_err(|e| {
        error!("❌ Scanner failed: {}", e);
        format!("Failed to scan components: {}", e)
    })?;

    // Get final counts from shared state
    let components_count = *total_components.lock().unwrap();
    let new_components = *new_components_count.lock().unwrap();
    let new_bundles = *new_bundles_count.lock().unwrap();

    info!("✅ Model scan and discovery complete");
    info!("   Total components found: {}", components_count);
    info!("   New components added: {}", new_components);
    info!("   Bundles created: {}", new_bundles);

    // Emit completion event
    let _ = app_state.app_handle.emit("model-scan-progress", serde_json::json!({
        "stage": "complete",
        "message": format!("Scan complete: {} components, {} bundles", components_count, new_bundles),
        "progress": 100
    }));

    Ok(ScanResult {
        components_found: components_count,
        components_added: new_components,
        bundles_created: new_bundles,
    })
}

/// Scan a specific directory for model files (not HuggingFace cache)
/// Identifies model types by inspecting file headers
#[command]
async fn scan_directory_for_models(
    app_state: State<'_, AppState>,
    directory_path: String,
    compute_hashes: Option<bool>,
) -> Result<ScanResult, String> {
    use crate::models::{scan_directory_for_models as scan_dir, scan_directory_for_models_fast as scan_dir_fast, to_component_record};
    use std::path::Path;
    use std::sync::{Arc, Mutex as StdMutex};

    let dir_path = Path::new(&directory_path);
    let should_hash = compute_hashes.unwrap_or(false);

    info!("🔄 ========================================");
    info!("🔄 scan_directory_for_models COMMAND CALLED");
    info!("🔄 Directory: {}", directory_path);
    info!("🔄 Compute hashes: {}", should_hash);
    info!("🔄 ========================================");

    // Emit scan start event
    let _ = app_state.app_handle.emit("model-scan-progress", serde_json::json!({
        "stage": "discovering",
        "message": "Discovering model files...",
        "progress": 0
    }));

    // Shared counter for new components
    let new_components_count = Arc::new(StdMutex::new(0usize));

    // Progress callback
    let app_handle = app_state.app_handle.clone();
    let progress_callback = Box::new(move |current: usize, total: usize, filename: &str| {
        let progress = (current * 100 / total.max(1)) as u8;
        let _ = app_handle.emit("model-scan-progress", serde_json::json!({
            "stage": "identifying",
            "message": format!("[{}/{}] Identifying: {}", current, total, filename),
            "progress": progress,
            "filesProcessed": current,
            "filesFound": total
        }));
    });

    // Run the scan (with or without hash computation)
    let components = if should_hash {
        // Hash progress callback
        let app_handle2 = app_state.app_handle.clone();
        let hash_callback = Box::new(move |filename: &str, percent: u8, processed: u64, total: u64| {
            let processed_mb = processed as f64 / 1_000_000.0;
            let total_mb = total as f64 / 1_000_000.0;
            let _ = app_handle2.emit("model-scan-progress", serde_json::json!({
                "stage": "hashing",
                "message": format!("Computing hash: {} ({}% - {:.1}/{:.1} MB)", filename, percent, processed_mb, total_mb),
                "progress": percent
            }));
        });
        scan_dir(dir_path, Some(progress_callback), Some(hash_callback))
    } else {
        scan_dir_fast(dir_path, Some(progress_callback))
    }.map_err(|e| format!("Scan failed: {}", e))?;

    let components_count = components.len();

    if components.is_empty() {
        info!("⚠️  No model components found in directory");
        let _ = app_state.app_handle.emit("model-scan-progress", serde_json::json!({
            "stage": "complete",
            "message": "No model files found",
            "progress": 100
        }));

        return Ok(ScanResult {
            components_found: 0,
            components_added: 0,
            bundles_created: 0,
        });
    }

    // Save components to database and create bundles
    let _ = app_state.app_handle.emit("model-scan-progress", serde_json::json!({
        "stage": "processing",
        "message": "Saving components to database...",
        "progress": 80
    }));

    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;

    let components = models::filter_sharded_components(components);

    for component in &components {
        // Convert to database record
        let record = to_component_record(component);

        // Check if component already exists
        if db.get_component(&record.id).is_ok() {
            info!("   - Component already exists: {}", record.name);
            continue;
        }

        // Insert new component
        match db.insert_component(&record) {
            Ok(_) => {
                *new_components_count.lock().unwrap() += 1;
                info!("   ✓ Added new component: {} ({:?})", record.name, component.component_type);
            }
            Err(e) => {
                warn!("   ✗ Failed to save component: {}", e);
            }
        }
    }

    let new_components = *new_components_count.lock().unwrap();

    info!("✅ Directory scan complete");
    info!("   Components found: {}", components_count);
    info!("   New components added: {}", new_components);

    // Emit completion event
    let _ = app_state.app_handle.emit("model-scan-progress", serde_json::json!({
        "stage": "complete",
        "message": format!("Scan complete: {} components found, {} new", components_count, new_components),
        "progress": 100
    }));

    Ok(ScanResult {
        components_found: components_count,
        components_added: new_components,
        bundles_created: 0,
    })
}

/// Convert a ComfyUI/InvokeAI format model to native FLUX format
#[command]
async fn convert_comfyui_model(
    app_state: State<'_, AppState>,
    input_path: String,
    output_path: Option<String>,
) -> Result<String, String> {
    use crate::models::convert_comfyui_to_native;
    use std::path::Path;

    info!("🔄 ========================================");
    info!("🔄 convert_comfyui_model COMMAND CALLED");
    info!("🔄 Input: {}", input_path);
    if let Some(ref out) = output_path {
        info!("🔄 Output: {}", out);
    } else {
        info!("🔄 Output: (auto-generated)");
    }
    info!("🔄 ========================================");

    let input = Path::new(&input_path);
    let output = output_path.as_ref().map(|p| Path::new(p.as_str()));

    // Emit conversion start event
    let _ = app_state.app_handle.emit("model-conversion-progress", serde_json::json!({
        "stage": "starting",
        "message": "Starting ComfyUI format conversion...",
        "progress": 0
    }));

    // Perform conversion
    match convert_comfyui_to_native(input, output) {
        Ok(output_path) => {
            let output_str = output_path.to_string_lossy().to_string();

            // Emit completion event
            let _ = app_state.app_handle.emit("model-conversion-progress", serde_json::json!({
                "stage": "complete",
                "message": "Conversion complete!",
                "progress": 100,
                "outputPath": &output_str
            }));

            info!("✅ Conversion successful: {}", output_str);
            Ok(output_str)
        }
        Err(e) => {
            let error_msg = format!("Conversion failed: {}", e);
            warn!("❌ {}", error_msg);

            // Emit error event
            let _ = app_state.app_handle.emit("model-conversion-progress", serde_json::json!({
                "stage": "error",
                "message": &error_msg,
                "progress": 0
            }));

            Err(error_msg)
        }
    }
}

/// Get all bundles with component details
#[command]
async fn get_all_bundles(
    app_state: State<'_, AppState>,
) -> Result<Vec<db::BundleInfoResponse>, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.get_all_bundles_response().map_err(|e| e.to_string())
}

/// Get a specific bundle by ID
#[command]
async fn get_bundle(
    app_state: State<'_, AppState>,
    bundle_id: String,
) -> Result<db::BundleInfo, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.get_bundle(&bundle_id).map_err(|e| e.to_string())
}

/// Create a new bundle
#[command]
async fn create_bundle(
    app_state: State<'_, AppState>,
    display_name: String,
    description: Option<String>,
    items: Vec<(String, String)>,
) -> Result<String, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;

    // Validate components exist and infer family from transformer
    let mut model_family = "other".to_string();
    for (role, comp_id) in &items {
        let comp = db.get_component(comp_id)
            .map_err(|e| format!("Component for role '{}' not found: {}", role, e))?;
        if role == "transformer" {
            model_family = match comp.architecture.as_deref() {
                Some(a) if a.contains("z-image") => "zindex".to_string(),
                Some(a) if a.contains("flux") || a.contains("schnell") || a.contains("dev") => "flux".to_string(),
                _ => "other".to_string(),
            };
        }
    }

    let bundle_id = uuid::Uuid::new_v4().to_string();
    let now = chrono::Utc::now().timestamp();

    let total_vram: i32 = items.iter()
        .filter_map(|(_, comp_id)| {
            db.get_component(comp_id).ok().and_then(|c| c.vram_mb)
        })
        .sum();

    let bundle = db::BundleRecord {
        id: bundle_id.clone(),
        name: display_name,
        description,
        bundle_type: "user_created".to_string(),
        model_family,
        default_steps: Some(4),
        default_guidance: Some(3.5),
        step_min: Some(1),
        step_max: Some(50),
        total_vram_mb: Some(total_vram),
        is_complete: items.len() >= 4,
        is_active: false,
        created_at: now,
        updated_at: now,
        validation_errors: None,
    };

    db.insert_bundle(&bundle)
        .map_err(|e| format!("Failed to create bundle: {}", e))?;

    for (role, comp_id) in &items {
        db.add_component_to_bundle(&bundle_id, comp_id, role, true, 0)
            .map_err(|e| format!("Failed to add component '{}' to bundle: {}", role, e))?;
    }

    Ok(bundle_id)
}

/// Update a bundle
#[command]
async fn update_bundle(
    app_state: State<'_, AppState>,
    bundle_id: String,
    display_name: Option<String>,
    description: Option<String>,
) -> Result<(), String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;

    db.update_bundle(&bundle_id, display_name.as_deref(), description.as_deref())
        .map_err(|e| e.to_string())
}

/// Delete a bundle
#[command]
async fn delete_bundle(
    app_state: State<'_, AppState>,
    bundle_id: String,
) -> Result<(), String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.delete_bundle(&bundle_id).map_err(|e| e.to_string())
}

/// Set a bundle as active (deactivates all others)
#[command]
async fn set_active_bundle(
    app_state: State<'_, AppState>,
    bundle_id: String,
) -> Result<(), String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.set_bundle_active(&bundle_id, true).map_err(|e| e.to_string())
}

/// Get available components for bundle creation
#[command]
async fn get_available_components(
    app_state: State<'_, AppState>,
) -> Result<Vec<db::ComponentRecord>, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.get_all_components().map_err(|e| e.to_string())
}

/// Get all models as ModelInfoResponse
#[command]
async fn get_all_models(
    app_state: State<'_, AppState>,
) -> Result<Vec<db::ModelInfoResponse>, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.get_all_models_response().map_err(|e| e.to_string())
}

/// Update model display name or description
#[command]
async fn update_model(
    app_state: State<'_, AppState>,
    model_id: String,
    display_name: Option<String>,
    _description: Option<String>,
) -> Result<(), String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;

    if let Some(name) = display_name {
        db.update_model_name(&model_id, &name).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Add a tag to a model
#[command]
async fn add_model_tag(
    app_state: State<'_, AppState>,
    model_id: String,
    tag: String,
) -> Result<(), String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.add_model_tag(&model_id, &tag).map_err(|e| e.to_string())
}

/// Remove a tag from a model
#[command]
async fn remove_model_tag(
    app_state: State<'_, AppState>,
    model_id: String,
    tag: String,
) -> Result<(), String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.remove_model_tag(&model_id, &tag).map_err(|e| e.to_string())
}

/// Add an example to a model or bundle
#[command]
async fn add_example(
    app_state: State<'_, AppState>,
    entity_type: String,
    entity_id: String,
    example_type: String,
    content: String,
) -> Result<String, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.add_example(&entity_type, &entity_id, &example_type, &content)
        .map_err(|e| e.to_string())
}

/// Remove an example by ID
#[command]
async fn remove_example(
    app_state: State<'_, AppState>,
    example_id: String,
) -> Result<(), String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.remove_example(&example_id).map_err(|e| e.to_string())
}

/// Get compatible models for a base model and target type
#[command]
async fn get_compatible_models(
    app_state: State<'_, AppState>,
    base_model_id: String,
    target_type: String,
) -> Result<Vec<db::ModelInfoResponse>, String> {
    let db_guard = app_state.inference_db.lock().await;
    let db = db_guard.as_ref()
        .ok_or_else(|| "Database not initialized".to_string())?;
    db.get_compatible_models(&base_model_id, &target_type)
        .map_err(|e| e.to_string())
}

// ========== End of Bundle System Commands ==========

#[command]
async fn get_hf_token(app_state: State<'_, AppState>) -> Result<Option<String>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_setting("hf_token").map_err(|e| e.to_string())
}

#[command]
async fn set_hf_token(
    app_state: State<'_, AppState>,
    token: Option<String>,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    if let Some(token) = token.filter(|t| !t.trim().is_empty()) {
        db.set_setting("hf_token", &token).map_err(|e| e.to_string())?;
    } else {
        db.delete_setting("hf_token").map_err(|e| e.to_string())?;
    }

    Ok("HuggingFace token saved".to_string())
}

#[command]
async fn get_claude_api_key(app_state: State<'_, AppState>) -> Result<Option<String>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_setting("claude_api_key").map_err(|e| e.to_string())
}

#[command]
async fn set_claude_api_key(
    app_state: State<'_, AppState>,
    key: Option<String>,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    if let Some(key) = key.filter(|k| !k.trim().is_empty()) {
        db.set_setting("claude_api_key", &key).map_err(|e| e.to_string())?;
    } else {
        db.delete_setting("claude_api_key").map_err(|e| e.to_string())?;
    }

    Ok("Claude API key saved".to_string())
}

#[command]
async fn get_fal_key(app_state: State<'_, AppState>) -> Result<Option<String>, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_setting("fal_key").map_err(|e| e.to_string())
}

#[command]
async fn set_fal_key(
    app_state: State<'_, AppState>,
    key: Option<String>,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    if let Some(key) = key.filter(|k| !k.trim().is_empty()) {
        db.set_setting("fal_key", &key).map_err(|e| e.to_string())?;
    } else {
        db.delete_setting("fal_key").map_err(|e| e.to_string())?;
    }

    Ok("Fal.ai key saved".to_string())
}

/// Read generation metadata from a PNG image
///
/// # Arguments
/// * `image_path` - Path to the PNG image file
///
/// # Returns
/// JSON object with generation parameters if metadata is found, null otherwise
#[command]
async fn read_image_metadata(image_path: String) -> Result<Option<serde_json::Value>, String> {
    use inference::metadata::read_png_metadata_from_file;

    let path = std::path::Path::new(&image_path);
    if !path.exists() {
        return Err(format!("File not found: {}", image_path));
    }

    let metadata = read_png_metadata_from_file(path)
        .map_err(|e| format!("Failed to read metadata: {}", e))?;

    match metadata {
        Some(m) => Ok(Some(serde_json::to_value(m).map_err(|e| e.to_string())?)),
        None => Ok(None),
    }
}

// ========== Model Cache Commands ==========

/// Get current model cache statistics
#[command]
async fn get_cache_stats(
    app_state: State<'_, AppState>,
) -> Result<inference::CacheStats, String> {
    let stats = app_state.queue_processor.model_cache().get_stats().await;
    Ok(stats)
}

/// Clear all cached models and embeddings
#[command]
async fn clear_model_cache(
    app_state: State<'_, AppState>,
) -> Result<String, String> {
    app_state.queue_processor.model_cache().clear().await;
    Ok("Model cache cleared".to_string())
}

/// Get current cache configuration
#[command]
async fn get_cache_config(
    app_state: State<'_, AppState>,
) -> Result<CacheConfigResponse, String> {
    let config = app_state.queue_processor.model_cache().get_config().await;
    Ok(CacheConfigResponse {
        keep_vae_loaded: config.keep_vae_loaded,
        keep_flux_loaded: config.keep_flux_loaded,
        keep_t5_loaded: config.keep_t5_loaded,
        keep_clip_loaded: config.keep_clip_loaded,
        embedding_cache_size: config.embedding_cache_size,
        idle_timeout_secs: config.idle_timeout_secs,
    })
}

#[derive(serde::Serialize, serde::Deserialize)]
struct CacheConfigResponse {
    keep_vae_loaded: bool,
    keep_flux_loaded: bool,
    keep_t5_loaded: bool,
    keep_clip_loaded: bool,
    embedding_cache_size: usize,
    idle_timeout_secs: Option<u64>,
}

/// Update cache configuration
#[command]
async fn set_cache_config(
    app_state: State<'_, AppState>,
    keep_vae_loaded: Option<bool>,
    keep_flux_loaded: Option<bool>,
    keep_t5_loaded: Option<bool>,
    keep_clip_loaded: Option<bool>,
    embedding_cache_size: Option<usize>,
    idle_timeout_secs: Option<u64>,
) -> Result<String, String> {
    let cache = app_state.queue_processor.model_cache();
    let mut config = cache.get_config().await;

    // Update only provided fields
    if let Some(v) = keep_vae_loaded {
        config.keep_vae_loaded = v;
    }
    if let Some(v) = keep_flux_loaded {
        config.keep_flux_loaded = v;
    }
    if let Some(v) = keep_t5_loaded {
        config.keep_t5_loaded = v;
    }
    if let Some(v) = keep_clip_loaded {
        config.keep_clip_loaded = v;
    }
    if let Some(v) = embedding_cache_size {
        config.embedding_cache_size = v;
    }
    // For idle_timeout_secs, we need special handling since None means "no timeout"
    // We use 0 to mean "disable timeout"
    if let Some(v) = idle_timeout_secs {
        config.idle_timeout_secs = if v == 0 { None } else { Some(v) };
    }

    cache.set_config(config).await;
    Ok("Cache configuration updated".to_string())
}

/// Apply a cache configuration preset
#[command]
async fn set_cache_preset(
    app_state: State<'_, AppState>,
    preset: String,
) -> Result<String, String> {
    use inference::ModelCacheConfig;

    let config = match preset.as_str() {
        "default" => ModelCacheConfig::default(),
        "keep_all" => ModelCacheConfig::keep_all_loaded(),
        "memory_saver" => ModelCacheConfig::memory_saver(),
        _ => return Err(format!("Unknown preset: {}. Use 'default', 'keep_all', or 'memory_saver'", preset)),
    };

    app_state.queue_processor.model_cache().set_config(config).await;
    Ok(format!("Cache preset '{}' applied", preset))
}

// ========== Auto-Tagging Commands ==========

/// Get the current vision model (Moondream) download status
#[command]
async fn check_vision_model_status() -> vision::VisionModelStatus {
    // Use spawn_blocking to avoid blocking the main thread
    // since the HuggingFace Hub API does synchronous I/O
    tokio::task::spawn_blocking(vision::get_model_status)
        .await
        .unwrap_or_default()
}

/// Download the Moondream vision model for local tagging
#[command]
async fn download_vision_model(
    app_handle: tauri::AppHandle,
    app_state: State<'_, AppState>,
) -> Result<String, String> {
    // Check if download is already in progress
    {
        let mut in_progress = app_state.download_in_progress.lock().await;
        if *in_progress {
            return Err("Download already in progress".to_string());
        }
        *in_progress = true;
    }

    let result = vision::download_moondream(Some(&app_handle))
        .await
        .map(|_| "Vision model downloaded successfully".to_string())
        .map_err(|e| e.to_string());

    // Reset the flag
    *app_state.download_in_progress.lock().await = false;

    result
}

/// Clear stale lock files that may be blocking vision model downloads
///
/// Call this if downloads are failing with "Lock acquisition failed" errors.
#[command]
async fn clear_vision_model_locks() -> Result<String, String> {
    tokio::task::spawn_blocking(|| {
        vision::force_cleanup_locks()
            .map(|count| {
                if count > 0 {
                    format!("Removed {} lock file(s)", count)
                } else {
                    "No lock files found".to_string()
                }
            })
            .map_err(|e| format!("Failed to clear locks: {}", e))
    })
    .await
    .map_err(|e| format!("Task failed: {}", e))?
}

/// Get auto-tagging settings from the gallery database
#[command]
async fn get_auto_tag_settings(
    app_state: State<'_, AppState>,
) -> Result<vision::AutoTagSettings, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    Ok(db.get_auto_tag_settings().unwrap_or_default())
}

/// Update auto-tagging settings in the gallery database
#[command]
async fn update_auto_tag_settings(
    app_state: State<'_, AppState>,
    settings: vision::AutoTagSettings,
) -> Result<String, String> {
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.set_auto_tag_settings(&settings)
        .map_err(|e| format!("Failed to save settings: {}", e))?;

    Ok("Auto-tag settings saved".to_string())
}

/// Auto-tag images using the specified backend
///
/// # Arguments
/// * `image_ids` - List of image IDs to tag
/// * `backend` - Optional backend preference ("local" or "claude"). Uses settings default if not provided.
#[command]
async fn auto_tag_images(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    backend: Option<String>,
) -> Result<Vec<vision::TaggingResult>, String> {
    use tracing::{info, warn};

    // Phase 1: Get settings and image paths from database, then release lock
    let (settings, image_paths, mut results, effective_backend) = {
        let db = app_state.inference_db.lock().await;
        let db = db.as_ref().ok_or("Database not initialized")?;

        // Get settings
        let settings = db.get_auto_tag_settings().unwrap_or_default();

        // Determine backend to use
        let requested_backend = backend
            .and_then(|b| b.parse::<vision::TaggingBackend>().ok())
            .unwrap_or(settings.preferred_backend);

        let effective_backend = match requested_backend {
            vision::TaggingBackend::Local => {
                if vision::is_moondream_downloaded() {
                    Some(vision::TaggingBackend::Local)
                } else if settings.is_claude_available() {
                    warn!("Local model not available, falling back to Claude");
                    Some(vision::TaggingBackend::Claude)
                } else {
                    None
                }
            }
            vision::TaggingBackend::Claude => {
                if settings.is_claude_available() {
                    Some(vision::TaggingBackend::Claude)
                } else if vision::is_moondream_downloaded() {
                    warn!("Claude API not available, falling back to local");
                    Some(vision::TaggingBackend::Local)
                } else {
                    None
                }
            }
        };

        let effective_backend = effective_backend
            .ok_or("No tagging backend available. Download Moondream or configure Claude API key.")?;

        let mut results = Vec::with_capacity(image_ids.len());
        let mut image_paths = Vec::new();

        // Get image paths
        for id in &image_ids {
            match db.get_image_by_id(id) {
                Ok(Some(img)) => {
                    if let Some(file_path) = img.file_path {
                        image_paths.push((id.clone(), std::path::PathBuf::from(file_path)));
                    } else {
                        results.push(vision::TaggingResult {
                            image_id: id.clone(),
                            tags: vec![],
                            backend: effective_backend,
                            success: false,
                            error: Some("Image file not available (pending generation)".to_string()),
                        });
                    }
                }
                Ok(None) => {
                    results.push(vision::TaggingResult {
                        image_id: id.clone(),
                        tags: vec![],
                        backend: effective_backend,
                        success: false,
                        error: Some("Image not found".to_string()),
                    });
                }
                Err(e) => {
                    results.push(vision::TaggingResult {
                        image_id: id.clone(),
                        tags: vec![],
                        backend: effective_backend,
                        success: false,
                        error: Some(format!("Database error: {}", e)),
                    });
                }
            }
        }

        (settings, image_paths, results, effective_backend)
    }; // Database lock released here

    info!(
        backend = %effective_backend,
        count = image_paths.len(),
        "Starting auto-tagging"
    );

    // Phase 2: Process images (no database lock held)
    let mut tagging_results: Vec<(String, Result<Vec<vision::TagWithConfidence>, String>)> = Vec::new();

    match effective_backend {
        vision::TaggingBackend::Local => {
            // Use local Moondream model (currently stub)
            use candle_core::Device;
            let device = Device::cuda_if_available(0).unwrap_or(Device::Cpu);

            match vision::MoondreamTagger::new(device) {
                Ok(mut tagger) => {
                    for (image_id, path) in image_paths {
                        info!(image_id = %image_id, path = %path.display(), "Processing image with Moondream");
                        let result = tagger.extract_tags(&path)
                            .map(|mut tags| {
                                info!(tag_count = tags.len(), "Tags extracted successfully");
                                tags.retain(|t| t.confidence >= settings.min_confidence);
                                tags
                            })
                            .map_err(|e| {
                                warn!(error = %e, "Failed to extract tags from image");
                                e.to_string()
                            });
                        tagging_results.push((image_id, result));
                    }
                }
                Err(e) => {
                    warn!(error = %e, "Failed to load Moondream model");
                    // If model loading fails, mark all as failed
                    for (image_id, _) in image_paths {
                        tagging_results.push((image_id, Err(format!("Failed to load model: {}", e))));
                    }
                }
            }
        }
        vision::TaggingBackend::Claude => {
            // Use Claude Vision API
            let api_key = settings.claude_api_key.clone()
                .ok_or("Claude API key not configured")?;

            let tagger = vision::ClaudeTagger::new(api_key);

            for (image_id, path) in image_paths {
                let result = tagger.extract_tags(&path).await
                    .map(|mut tags| {
                        tags.retain(|t| t.confidence >= settings.min_confidence);
                        tags
                    })
                    .map_err(|e| e.to_string());
                tagging_results.push((image_id, result));
            }
        }
    }

    // Phase 3: Save tags to database
    {
        let db = app_state.inference_db.lock().await;
        let db = db.as_ref().ok_or("Database not initialized")?;

        for (image_id, result) in tagging_results {
            match result {
                Ok(tags) => {
                    // Save tags to database
                    if let Err(e) = db.bulk_add_tags_with_category(&image_id, &tags) {
                        warn!(error = %e, "Failed to save tags to database");
                    }

                    results.push(vision::TaggingResult {
                        image_id,
                        tags,
                        backend: effective_backend,
                        success: true,
                        error: None,
                    });
                }
                Err(e) => {
                    results.push(vision::TaggingResult {
                        image_id,
                        tags: vec![],
                        backend: effective_backend,
                        success: false,
                        error: Some(e),
                    });
                }
            }
        }
    }

    info!(
        success_count = results.iter().filter(|r| r.success).count(),
        total = results.len(),
        "Auto-tagging complete"
    );

    Ok(results)
}

// ========== LoRA Commands ==========

/// Get all available LoRAs
#[command]
async fn get_loras(
    app_state: State<'_, AppState>,
) -> Result<Vec<models::LoraInfo>, String> {
    let lora_manager = app_state.queue_processor.lora_manager().lock().await;
    lora_manager.scan_loras().await.map_err(|e| e.to_string())
}

/// Import a LoRA from a local file
#[command]
async fn import_lora(
    app_state: State<'_, AppState>,
    source_path: String,
    name: String,
    trigger_words: Option<String>,
) -> Result<models::LoraInfo, String> {
    let lora_manager = app_state.queue_processor.lora_manager().lock().await;
    lora_manager
        .import_lora(
            std::path::Path::new(&source_path),
            &name,
            trigger_words.as_deref(),
        )
        .await
        .map_err(|e| e.to_string())
}

/// Remove a LoRA from the collection
#[command]
async fn remove_lora(
    app_state: State<'_, AppState>,
    id: String,
) -> Result<String, String> {
    let lora_manager = app_state.queue_processor.lora_manager().lock().await;
    lora_manager.remove_lora(&id).await.map_err(|e| e.to_string())?;
    Ok("LoRA removed".to_string())
}

/// Update LoRA metadata
#[command]
async fn update_lora(
    app_state: State<'_, AppState>,
    id: String,
    name: Option<String>,
    trigger_words: Option<Option<String>>,
) -> Result<models::LoraInfo, String> {
    let lora_manager = app_state.queue_processor.lora_manager().lock().await;

    // Convert trigger_words: Option<Option<String>> to Option<Option<&str>>
    // None = don't change, Some(None) = clear, Some(Some(s)) = set to s
    let tw_ref = trigger_words.as_ref().map(|opt| opt.as_deref());

    lora_manager
        .update_lora(&id, name.as_deref(), tw_ref)
        .await
        .map_err(|e| e.to_string())
}

/// Get file info for a LoRA without importing it
#[command]
async fn get_lora_file_info(
    app_state: State<'_, AppState>,
    path: String,
) -> Result<models::LoraFileInfo, String> {
    let lora_manager = app_state.queue_processor.lora_manager().lock().await;
    lora_manager
        .get_file_info(std::path::Path::new(&path))
        .map_err(|e| e.to_string())
}

// ========== System Stats Commands ==========

#[derive(serde::Serialize)]
struct SystemStats {
    /// CPU usage as percentage (0-100)
    cpu_usage: f32,
    /// Memory used in bytes
    memory_used: u64,
    /// Total memory in bytes
    memory_total: u64,
    /// Memory usage as percentage (0-100)
    memory_percent: f32,
    /// GPU memory used in bytes (if available)
    gpu_memory_used: Option<u64>,
    /// GPU memory total in bytes (if available)
    gpu_memory_total: Option<u64>,
    /// GPU usage percentage (if available)
    gpu_usage_percent: Option<f32>,
    /// GPU name (if available)
    gpu_name: Option<String>,
    /// Whether a generation is currently running
    is_generating: bool,
}

/// Get current system resource usage (CPU, RAM, GPU)
#[command]
async fn get_system_stats(
    app_state: State<'_, AppState>,
) -> Result<SystemStats, String> {
    use sysinfo::System;

    let mut sys = System::new();
    sys.refresh_cpu_all();
    sys.refresh_memory();

    // Wait a bit for CPU readings to stabilize
    tokio::time::sleep(tokio::time::Duration::from_millis(100)).await;
    sys.refresh_cpu_all();

    // Calculate average CPU usage across all cores
    let cpu_usage: f32 = sys.cpus().iter().map(|cpu| cpu.cpu_usage()).sum::<f32>()
        / sys.cpus().len().max(1) as f32;

    let memory_used = sys.used_memory();
    let memory_total = sys.total_memory();
    let memory_percent = if memory_total > 0 {
        (memory_used as f64 / memory_total as f64 * 100.0) as f32
    } else {
        0.0
    };

    // Check if generating
    let is_generating = {
        let jobs = app_state.queue_manager.get_jobs().await;
        jobs.iter().any(|j| j.status == queue::JobStatus::Running)
    };

    // Try to get GPU stats via CUDA (Linux) or nvml
    let (gpu_memory_used, gpu_memory_total, gpu_usage_percent, gpu_name) = get_gpu_stats();

    Ok(SystemStats {
        cpu_usage,
        memory_used,
        memory_total,
        memory_percent,
        gpu_memory_used,
        gpu_memory_total,
        gpu_usage_percent,
        gpu_name,
        is_generating,
    })
}

/// Get GPU stats using nvidia-smi (cross-platform fallback)
fn get_gpu_stats() -> (Option<u64>, Option<u64>, Option<f32>, Option<String>) {
    // Try to run nvidia-smi to get GPU stats
    let output = std::process::Command::new("nvidia-smi")
        .args([
            "--query-gpu=memory.used,memory.total,utilization.gpu,name",
            "--format=csv,noheader,nounits",
        ])
        .output();

    match output {
        Ok(output) if output.status.success() => {
            let stdout = String::from_utf8_lossy(&output.stdout);
            let line = stdout.lines().next().unwrap_or("");
            let parts: Vec<&str> = line.split(',').map(|s| s.trim()).collect();

            if parts.len() >= 4 {
                let mem_used = parts[0].parse::<u64>().ok().map(|v| v * 1024 * 1024); // MiB to bytes
                let mem_total = parts[1].parse::<u64>().ok().map(|v| v * 1024 * 1024);
                let gpu_util = parts[2].parse::<f32>().ok();
                let gpu_name = Some(parts[3].to_string());

                return (mem_used, mem_total, gpu_util, gpu_name);
            }
        }
        _ => {}
    }

    (None, None, None, None)
}

/// Emit a job update event to both Tauri and WebSocket (if in server mode)
pub async fn emit_job_update(
    app_state: &AppState,
    job_id: &str,
    status: &str,
    progress: f32,
    result_path: Option<&str>,
    error: Option<&str>,
) {
    // Emit to Tauri (for desktop UI)
    let mut payload = serde_json::json!({
        "job_id": job_id,
        "status": status,
        "progress": progress,
    });

    // Add result_path if available
    if let Some(path) = result_path {
        payload["result_path"] = serde_json::json!(path);
    }

    // Add error if available
    if let Some(err) = error {
        payload["error"] = serde_json::json!(err);
    }

    let _ = app_state.app_handle.emit("job-update", payload);

    // Emit to WebSocket (if in server mode)
    if let Some(ws_state) = &app_state.ws_state {
        let message = if status == "completed" && result_path.is_some() {
            server::websocket::ServerMessage::JobComplete {
                job_id: job_id.to_string(),
                result_url: format!("/api/v1/files/{}",
                    std::path::Path::new(result_path.unwrap())
                        .file_name()
                        .and_then(|n| n.to_str())
                        .unwrap_or("")
                ),
            }
        } else if status == "failed" && error.is_some() {
            server::websocket::ServerMessage::JobFailed {
                job_id: job_id.to_string(),
                error: error.unwrap().to_string(),
            }
        } else {
            server::websocket::ServerMessage::JobProgress {
                job_id: job_id.to_string(),
                status: status.to_string(),
                progress,
                stage: None,
                current_step: None,
                total_steps: None,
            }
        };

        server::websocket::broadcast_job_update(ws_state, job_id, message).await;
    }
}

/// Get the runtime configuration (mode, server URL, etc.)
#[command]
fn get_runtime_config(app_state: State<'_, AppState>) -> shared::protocol::RuntimeConfig {
    app_state.runtime_config.clone()
}

// ========== Client Mode Commands ==========

/// Add a job to queue (client mode aware)
#[command]
async fn client_add_to_queue(
    app_state: State<'_, AppState>,
    params: queue::GenerationParams,
) -> Result<String, String> {
    if let Some(client) = &app_state.client_api {
        // Client mode: Use REST API
        client.submit_job(params).await
            .map_err(|e| e.to_string())
    } else {
        // Local/Server mode: Use local queue
        add_to_queue(app_state, params).await
    }
}

/// Get all queue jobs (client mode aware)
#[command]
async fn client_get_queue_jobs(
    app_state: State<'_, AppState>,
) -> Result<Vec<queue::GenerationJob>, String> {
    if let Some(client) = &app_state.client_api {
        // Client mode: Use REST API
        client.get_jobs().await
            .map_err(|e| e.to_string())
    } else {
        // Local/Server mode: Use local queue
        get_queue_jobs(app_state).await
    }
}

/// Get a specific job (client mode aware)
#[command]
async fn client_get_queue_job(
    app_state: State<'_, AppState>,
    job_id: String,
) -> Result<Option<queue::GenerationJob>, String> {
    if let Some(client) = &app_state.client_api {
        // Client mode: Use REST API
        client.get_job(&job_id).await
            .map_err(|e| e.to_string())
    } else {
        // Local/Server mode: Use local queue
        Ok(app_state.queue_manager.get_job(&job_id).await)
    }
}

/// Cancel a job (client mode aware)
#[command]
async fn client_cancel_queue_job(
    app_state: State<'_, AppState>,
    job_id: String,
) -> Result<bool, String> {
    if let Some(client) = &app_state.client_api {
        // Client mode: Use REST API
        client.cancel_job(&job_id).await
            .map_err(|e| e.to_string())
    } else {
        // Local/Server mode: Use local queue
        cancel_queue_job(app_state, job_id).await
    }
}

/// Get the file URL for an image (client mode aware)
#[command]
fn client_get_file_url(
    app_state: State<'_, AppState>,
    filename: String,
) -> Result<String, String> {
    if let Some(client) = &app_state.client_api {
        // Client mode: Return server URL
        Ok(client.get_file_url(&filename))
    } else {
        // Local/Server mode: Return local file path
        let home = dirs::home_dir()
            .ok_or_else(|| "Could not determine home directory".to_string())?;
        let output_dir = home.join(".rzem-ai-inference").join("outputs");
        let file_path = output_dir.join(&filename);
        Ok(file_path.to_string_lossy().to_string())
    }
}

/// Analyze an image using Claude and generate a prompt to recreate it
///
/// # Arguments
/// * `image_data` - Base64-encoded image data (can include data URL prefix)
/// * `media_type` - Optional MIME type. If not provided, will be inferred from data URL.
#[command]
async fn analyze_image_for_prompt(
    app_state: State<'_, AppState>,
    image_data: String,
    media_type: Option<String>,
) -> Result<String, String> {
    // Load Claude API key from database
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    let api_key = db.get_setting("claude_api_key")
        .map_err(|e| e.to_string())?
        .ok_or_else(|| "Claude API key not configured. Please set it in Settings.".to_string())?;

    // Parse image data - handle both raw base64 and data URL formats
    let (base64_data, mime_type) = if image_data.starts_with("data:") {
        // Parse data URL: data:image/png;base64,xxxxx
        let parts: Vec<&str> = image_data.splitn(2, ',').collect();
        if parts.len() != 2 {
            return Err("Invalid data URL format".to_string());
        }

        // Extract MIME type from header
        let header = parts[0];
        let inferred_mime = header
            .strip_prefix("data:")
            .and_then(|s| s.split(';').next())
            .unwrap_or("image/png")
            .to_string();

        (parts[1].to_string(), media_type.unwrap_or(inferred_mime))
    } else {
        // Raw base64 - use provided media type or default
        (image_data, media_type.unwrap_or_else(|| "image/png".to_string()))
    };

    // Call Claude API to analyze the image
    claude::analyze_image_for_prompt(&api_key, &base64_data, &mime_type)
        .await
        .map_err(|e| e.to_string())
}

/// Refine a prompt using Claude AI chatbot
#[command]
async fn chat_refine_prompt(
    app_state: State<'_, AppState>,
    request: chatbot::RefineRequest,
) -> Result<chatbot::ChatResponse, String> {
    // Check if we're in client mode
    if let Some(client) = &app_state.client_api {
        // Client mode: Use REST API
        return client.chat_refine(request)
            .await
            .map_err(|e| e.to_string());
    }

    // Local/Server mode: Load API key from database
    let db = app_state.inference_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    let api_key = db.get_setting("claude_api_key")
        .map_err(|e| e.to_string())?
        .ok_or_else(|| "Claude API key not configured. Please set it in Settings.".to_string())?;

    chatbot::refine_prompt(&api_key, request)
        .await
        .map_err(|e| e.to_string())
}

/// Get all available model configurations
#[command]
async fn get_model_configs(
    app_state: State<'_, AppState>,
) -> Result<Vec<models::ModelConfig>, String> {
    let configs = app_state.model_config_cache.get_all().await;
    Ok(configs)
}

/// Get configuration for a specific model
#[command]
async fn get_model_config(
    app_state: State<'_, AppState>,
    model_id: String,
) -> Result<models::ModelConfig, String> {
    app_state.model_config_cache.get_config(&model_id).await
        .map_err(|e| e.to_string())
}

/// Reload model configurations from database
#[command]
async fn reload_model_configs(
    app_state: State<'_, AppState>,
) -> Result<(), String> {
    app_state.model_config_cache.invalidate().await;
    app_state.model_config_cache.load_all().await
        .map_err(|e| e.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    run_with_config(shared::protocol::RuntimeConfig::local(), None)
}

/// Run the application with a specific configuration
///
/// This is the main entry point that supports different operation modes
pub fn run_with_config(runtime_config: shared::protocol::RuntimeConfig, port: Option<u16>) {
    // Initialize logging (defaults to info level, use RUST_LOG to override)
    init_logging("info");

    let inference_db = Arc::new(Mutex::new(None));
    let queue_manager = Arc::new(queue::QueueManager::new(1)); // Max 1 concurrent for now
    let model_config_cache = Arc::new(models::ModelConfigCache::new(inference_db.clone()));

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .setup(move |app| {
            // Get app handle
            let app_handle = app.handle().clone();

            // Create WebSocket state if in server mode
            let ws_state = if runtime_config.mode == shared::protocol::OperationMode::Server {
                Some(Arc::new(server::ws_state::WsState::new()))
            } else {
                None
            };

            // Create client API if in client mode
            let client_api = if runtime_config.mode == shared::protocol::OperationMode::Client {
                if let Some(server_url) = &runtime_config.server_url {
                    let config = client::ClientConfig::new(server_url.clone());
                    Some(Arc::new(client::api::ApiClient::new(config)))
                } else {
                    tracing::error!("Client mode requires server URL");
                    None
                }
            } else {
                None
            };

            // Create processor with app handle (needs its own clone)
            let queue_processor = Arc::new(
                QueueProcessor::new(
                    queue_manager.clone(),
                    inference_db.clone(),
                    app_handle.clone(),
                    ws_state.clone(),
                ).expect("Failed to create queue processor")
            );

            // Store in managed state
            let app_state = Arc::new(AppState {
                inference_db: inference_db.clone(),
                queue_manager: queue_manager.clone(),
                queue_processor: queue_processor.clone(),
                model_config_cache: model_config_cache.clone(),
                app_handle: app_handle.clone(),
                download_in_progress: Arc::new(Mutex::new(false)),
                runtime_config: runtime_config.clone(),
                ws_state: ws_state.clone(),
                client_api: client_api.clone(),
            });

            app.manage(app_state.as_ref().clone());

            // Start processor
            tauri::async_runtime::spawn({
                let queue_processor = queue_processor.clone();
                async move {
                    queue_processor.start().await;
                }
            });


            // Initialize session management
            tauri::async_runtime::spawn({
                let inference_db = inference_db.clone();
                async move {
                    let db_guard = inference_db.lock().await;
                    if let Some(db) = db_guard.as_ref() {
                        // Cleanup: Mark any PENDING or PROCESSING images as FAILED (crash recovery)
                        match db.cleanup_pending_images() {
                            Ok(count) => {
                                if count > 0 {
                                    info!("Marked {} pending/processing images as failed on startup", count);
                                }
                            }
                            Err(e) => warn!("Failed to cleanup pending images: {}", e),
                        }

                        // Generate new session ID
                        let session_id = uuid::Uuid::new_v4().to_string();
                        if let Err(e) = db.set_setting("current_session_id", &session_id) {
                            warn!("Failed to set session ID: {}", e);
                        } else {
                            info!("Generated session ID: {}", session_id);
                        }
                    }
                }
            });

            // Start server if in server mode
            if runtime_config.mode == shared::protocol::OperationMode::Server {
                let port = port.unwrap_or(8080);
                tauri::async_runtime::spawn({
                    let app_state_for_server = app_state.clone();
                    async move {
                        match server::start_server(app_state_for_server, port, false).await {
                            Ok(addr) => {
                                tracing::info!("Server started at {}", addr);
                            }
                            Err(e) => {
                                tracing::error!("Failed to start server: {}", e);
                            }
                        }
                    }
                });
            }

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            health_check,
            get_runtime_config,
            // Client mode commands
            client_add_to_queue,
            client_get_queue_jobs,
            client_get_queue_job,
            client_cancel_queue_job,
            client_get_file_url,
            // Local commands
            init_database,
            generate_image,
            get_gallery_images,
            get_queue_images,
            get_history_images,
            search_gallery_images,
            toggle_favorite,
            add_image_tag,
            remove_image_tag,
            delete_gallery_image,
            add_to_queue,
            get_queue_jobs,
            get_queue_job,
            cancel_queue_job,
            clear_completed_jobs,
            // Folder commands
            create_folder,
            update_folder,
            delete_folder,
            move_folder,
            get_folder_tree,
            add_images_to_folder,
            remove_images_from_folder,
            get_folder_images,
            get_uncategorized_images,
            // Enhanced tag commands
            get_all_tags,
            update_tag,
            bulk_add_tag,
            bulk_remove_tag,
            delete_tag,
            // Folder reordering
            reorder_folders,
            // Model download commands
            download_flux_schnell,
            download_flux_dev,
            check_models_downloaded,
            get_model_status,
            scan_models,
            get_available_models,
            get_component_availability,
            // Model bundle system commands
            scan_and_discover_models,
            scan_directory_for_models,
            convert_comfyui_model,
            get_all_bundles,
            get_bundle,
            create_bundle,
            update_bundle,
            delete_bundle,
            set_active_bundle,
            get_available_components,
            get_all_models,
            update_model,
            add_model_tag,
            remove_model_tag,
            add_example,
            remove_example,
            get_compatible_models,
            // Model configuration commands
            get_model_configs,
            get_model_config,
            reload_model_configs,
            // Settings commands
            get_hf_token,
            set_hf_token,
            get_claude_api_key,
            set_claude_api_key,
            get_fal_key,
            set_fal_key,
            // Image analysis
            analyze_image_for_prompt,
            read_image_metadata,
            // Chatbot commands
            chat_refine_prompt,
            // Model cache commands
            get_cache_stats,
            clear_model_cache,
            get_cache_config,
            set_cache_config,
            set_cache_preset,
            // Auto-tagging commands
            check_vision_model_status,
            download_vision_model,
            clear_vision_model_locks,
            get_auto_tag_settings,
            update_auto_tag_settings,
            auto_tag_images,
            // System stats
            get_system_stats,
            // LoRA commands
            get_loras,
            import_lora,
            remove_lora,
            update_lora,
            get_lora_file_info,
            // Batch scripting commands
            batch::batch_parse_data,
            batch::batch_render_template,
            batch::batch_generate_combinations,
            batch::batch_get_recent_templates,
            batch::batch_save_template,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
