pub mod inference;
pub mod models;
mod queue;
mod gallery;
mod settings;
mod utils;
mod claude;
mod logging;
pub mod vision;

pub use logging::init_logging;

use tauri::{command, Manager, Emitter};
use std::sync::Arc;
use tauri::State;
use tokio::sync::Mutex;
use tracing::warn;
use queue::QueueProcessor;

struct AppState {
    gallery_db: Arc<Mutex<Option<gallery::GalleryDb>>>,
    queue_manager: Arc<queue::QueueManager>,
    queue_processor: Arc<QueueProcessor>,
    app_handle: tauri::AppHandle,
    download_in_progress: Arc<Mutex<bool>>,
}

#[command]
fn health_check() -> String {
    "OK".to_string()
}

#[command]
async fn init_database(app_state: State<'_, AppState>, db_path: String) -> Result<String, String> {
    // Create parent directory if it doesn't exist
    if let Some(parent) = std::path::Path::new(&db_path).parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create database directory: {}", e))?;
    }

    let db = gallery::GalleryDb::new(&db_path)
        .map_err(|e| format!("Failed to open database: {}", e))?;

    db.init_schema()
        .map_err(|e| format!("Failed to initialize schema: {}", e))?;

    *app_state.gallery_db.lock().await = Some(db);

    Ok("Database initialized".to_string())
}

/// Generate an image from a text prompt using Flux model
///
/// # Arguments
/// * `prompt` - Text description of image to generate
/// * `steps` - Number of diffusion steps
/// * `width` - Image width in pixels
/// * `height` - Image height in pixels
/// * `seed` - Random seed for generation (-1 for random)
///
/// # Returns
/// File path to the generated image
#[command]
async fn generate_image(
    app_state: State<'_, AppState>,
    prompt: String,
    steps: u32,
    width: u32,
    height: u32,
    seed: i64,
) -> Result<String, String> {
    use crate::inference::{InferenceEngine, FluxPipeline};
    use crate::gallery::ImageMetadata;
    use std::fs;

    // Get or create inference engine
    let engine = InferenceEngine::new()
        .map_err(|e| format!("Failed to initialize inference engine: {}", e))?;

    let device = engine.get_device().clone();
    let mut pipeline = FluxPipeline::new(device)
        .map_err(|e| format!("Failed to create pipeline: {}", e))?;

    // Generate image using FLUX
    // Convert seed to u64 (negative means use random)
    let seed_u64 = if seed >= 0 { seed as u64 } else { rand::random::<u64>() };
    let result = pipeline.generate(
        &prompt,
        steps as usize,
        width as usize,
        height as usize,
        4.0, // Default guidance for FLUX Schnell
        seed_u64,
        inference::SamplerType::default(),
        inference::SchedulerType::default(),
    ).map_err(|e| format!("Generation failed: {}", e))?;

    // Determine output path
    let home = dirs::home_dir()
        .ok_or_else(|| "Could not determine home directory".to_string())?;
    let output_dir = home.join(".rzem-ai-inference").join("outputs");

    // Create output directory
    fs::create_dir_all(&output_dir)
        .map_err(|e| format!("Failed to create output directory: {}", e))?;

    // Generate filename with timestamp
    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|e| format!("System time error: {}", e))?
        .as_secs();
    let filename = format!("flux_{}_{}.png", timestamp, seed);
    let output_path = output_dir.join(&filename);

    // Save PNG image data
    fs::write(&output_path, &result.image_data)
        .map_err(|e| format!("Failed to write image: {}", e))?;

    // Insert into gallery database
    let db = app_state.gallery_db.lock().await;
    if let Some(db) = db.as_ref() {
        let image_id = uuid::Uuid::new_v4().to_string();
        let metadata = ImageMetadata {
            id: image_id.clone(),
            file_path: output_path.to_string_lossy().to_string(),
            thumbnail_path: None, // Thumbnails are generated by the queue processor
            prompt: prompt.clone(),
            created_at: timestamp as i64,
        };
        if let Err(e) = db.insert_image(&metadata) {
            warn!(error = %e, "Failed to insert image into gallery");
        }
        // Store generation stats
        if let Err(e) = db.insert_generation_stats(&image_id, &result.stats) {
            warn!(error = %e, "Failed to insert generation stats");
        }
    }

    Ok(output_path.to_string_lossy().to_string())
}

#[command]
async fn get_gallery_images(
    app_state: State<'_, AppState>,
    limit: usize,
) -> Result<Vec<gallery::GalleryImage>, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_gallery_images(limit)
        .map_err(|e| format!("Failed to get images: {}", e))
}

#[command]
async fn search_gallery_images(
    app_state: State<'_, AppState>,
    query: String,
) -> Result<Vec<gallery::ImageMetadata>, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.search_gallery_images(&query)
        .map_err(|e| format!("Failed to search images: {}", e))
}

#[command]
async fn toggle_favorite(
    app_state: State<'_, AppState>,
    image_id: String,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.toggle_favorite(&image_id)
        .map_err(|e| format!("Failed to toggle favorite: {}", e))?;

    Ok("Favorite toggled".to_string())
}

#[command]
async fn add_image_tag(
    app_state: State<'_, AppState>,
    image_id: String,
    tag: String,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.add_image_tag(&image_id, &tag)
        .map_err(|e| format!("Failed to add tag: {}", e))?;

    Ok("Tag added".to_string())
}

#[command]
async fn remove_image_tag(
    app_state: State<'_, AppState>,
    image_id: String,
    tag: String,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.remove_image_tag(&image_id, &tag)
        .map_err(|e| format!("Failed to remove tag: {}", e))?;

    Ok("Tag removed".to_string())
}

#[command]
async fn delete_gallery_image(
    app_state: State<'_, AppState>,
    image_id: String,
) -> Result<String, String> {
    let db = app_state
        .gallery_db
        .lock()
        .await;

    let db = db.as_ref().ok_or("Database not initialized")?;

    // Get image metadata
    let image = db.get_image_by_id(&image_id)
        .map_err(|e| format!("Failed to get image: {}", e))?
        .ok_or_else(|| "Image not found".to_string())?;

    // Delete file from filesystem
    std::fs::remove_file(&image.file_path)
        .map_err(|e| format!("Failed to delete file: {}", e))?;

    // Delete from database (this will cascade to image_tags)
    db.delete_gallery_image(&image_id)
        .map_err(|e| format!("Failed to delete from database: {}", e))?;

    Ok("Image deleted".to_string())
}

// ========== Folder Commands ==========

#[command]
async fn create_folder(
    app_state: State<'_, AppState>,
    name: String,
    parent_id: Option<String>,
    color: Option<String>,
    icon: Option<String>,
) -> Result<gallery::Folder, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.create_folder(&name, parent_id.as_deref(), color.as_deref(), icon.as_deref())
        .map_err(|e| format!("Failed to create folder: {}", e))
}

#[command]
async fn update_folder(
    app_state: State<'_, AppState>,
    id: String,
    name: Option<String>,
    color: Option<String>,
    icon: Option<String>,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.update_folder(&id, name.as_deref(), color.as_deref(), icon.as_deref())
        .map_err(|e| format!("Failed to update folder: {}", e))?;

    Ok("Folder updated".to_string())
}

#[command]
async fn delete_folder(
    app_state: State<'_, AppState>,
    id: String,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.delete_folder(&id)
        .map_err(|e| format!("Failed to delete folder: {}", e))?;

    Ok("Folder deleted".to_string())
}

#[command]
async fn move_folder(
    app_state: State<'_, AppState>,
    id: String,
    new_parent_id: Option<String>,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.move_folder(&id, new_parent_id.as_deref())
        .map_err(|e| format!("Failed to move folder: {}", e))?;

    Ok("Folder moved".to_string())
}

#[command]
async fn get_folder_tree(
    app_state: State<'_, AppState>,
) -> Result<Vec<gallery::FolderNode>, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_folder_tree()
        .map_err(|e| format!("Failed to get folder tree: {}", e))
}

#[command]
async fn add_images_to_folder(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    folder_id: String,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.add_images_to_folder(&image_ids, &folder_id)
        .map_err(|e| format!("Failed to add images to folder: {}", e))?;

    Ok("Images added to folder".to_string())
}

#[command]
async fn remove_images_from_folder(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    folder_id: String,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.remove_images_from_folder(&image_ids, &folder_id)
        .map_err(|e| format!("Failed to remove images from folder: {}", e))?;

    Ok("Images removed from folder".to_string())
}

#[command]
async fn get_folder_images(
    app_state: State<'_, AppState>,
    folder_id: String,
    include_descendants: bool,
    limit: usize,
) -> Result<Vec<gallery::GalleryImage>, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_folder_images(&folder_id, include_descendants, limit)
        .map_err(|e| format!("Failed to get folder images: {}", e))
}

#[command]
async fn get_uncategorized_images(
    app_state: State<'_, AppState>,
    limit: usize,
) -> Result<Vec<gallery::GalleryImage>, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_uncategorized_images(limit)
        .map_err(|e| format!("Failed to get uncategorized images: {}", e))
}

// ========== Enhanced Tag Commands ==========

#[command]
async fn get_all_tags(
    app_state: State<'_, AppState>,
) -> Result<Vec<gallery::Tag>, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.get_all_tags()
        .map_err(|e| format!("Failed to get tags: {}", e))
}

#[command]
async fn update_tag(
    app_state: State<'_, AppState>,
    id: i64,
    name: Option<String>,
    color: Option<String>,
    category: Option<String>,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.update_tag(id, name.as_deref(), color.as_deref(), category.as_deref())
        .map_err(|e| format!("Failed to update tag: {}", e))?;

    Ok("Tag updated".to_string())
}

#[command]
async fn bulk_add_tag(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    tag: String,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.bulk_add_tag(&image_ids, &tag)
        .map_err(|e| format!("Failed to bulk add tag: {}", e))?;

    Ok("Tag added to images".to_string())
}

#[command]
async fn bulk_remove_tag(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    tag: String,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.bulk_remove_tag(&image_ids, &tag)
        .map_err(|e| format!("Failed to bulk remove tag: {}", e))?;

    Ok("Tag removed from images".to_string())
}

#[command]
async fn add_to_queue(
    app_state: State<'_, AppState>,
    params: queue::GenerationParams,
) -> Result<String, String> {
    let job_id = app_state.queue_manager.add_job(params).await;

    // Emit event for new job
    app_state.app_handle.emit("job-update", serde_json::json!({
        "job_id": job_id,
        "status": "pending",
        "progress": 0.0,
    })).map_err(|e| e.to_string())?;

    Ok(job_id)
}

#[command]
async fn get_queue_jobs(
    app_state: State<'_, AppState>,
) -> Result<Vec<queue::GenerationJob>, String> {
    let jobs = app_state.queue_manager.get_jobs().await;
    Ok(jobs)
}

#[command]
async fn get_queue_job(
    app_state: State<'_, AppState>,
    job_id: String,
) -> Result<Option<queue::GenerationJob>, String> {
    let job = app_state.queue_manager.get_job(&job_id).await;
    Ok(job)
}

#[command]
async fn cancel_queue_job(
    app_state: State<'_, AppState>,
    job_id: String,
) -> Result<bool, String> {
    let cancelled = app_state.queue_manager.cancel_job(&job_id).await;

    if cancelled {
        // Emit event for cancelled job
        app_state.app_handle.emit("job-update", serde_json::json!({
            "job_id": job_id,
            "status": "cancelled",
        })).map_err(|e| e.to_string())?;
    }

    Ok(cancelled)
}

#[command]
async fn clear_completed_jobs(
    app_state: State<'_, AppState>,
) -> Result<(), String> {
    app_state.queue_manager.clear_completed().await;
    Ok(())
}

#[command]
async fn download_flux_schnell(app_state: State<'_, AppState>) -> Result<String, String> {
    use crate::models::ModelDownloader;

    // Check if download is already in progress
    {
        let mut in_progress = app_state.download_in_progress.lock().await;
        if *in_progress {
            return Err("Download already in progress".to_string());
        }
        *in_progress = true;
    }

    // Ensure we reset the flag even on error
    let result = async {
        let downloader = ModelDownloader::new()
            .map_err(|e| e.to_string())?;

        if downloader.is_schnell_downloaded() {
            return Ok("FLUX Schnell is already downloaded".to_string());
        }

        downloader.download_schnell()
            .await
            .map_err(|e| e.to_string())?;

        Ok("FLUX Schnell downloaded successfully".to_string())
    }.await;

    // Reset the flag
    *app_state.download_in_progress.lock().await = false;

    result
}

#[command]
async fn download_flux_dev(app_state: State<'_, AppState>) -> Result<String, String> {
    use crate::models::ModelDownloader;

    // Check if download is already in progress
    {
        let mut in_progress = app_state.download_in_progress.lock().await;
        if *in_progress {
            return Err("Download already in progress".to_string());
        }
        *in_progress = true;
    }

    // Ensure we reset the flag even on error
    let result = async {
        let downloader = ModelDownloader::new()
            .map_err(|e| e.to_string())?;

        if downloader.is_dev_downloaded() {
            return Ok("FLUX Dev is already downloaded".to_string());
        }

        downloader.download_dev()
            .await
            .map_err(|e| e.to_string())?;

        Ok("FLUX Dev downloaded successfully".to_string())
    }.await;

    // Reset the flag
    *app_state.download_in_progress.lock().await = false;

    result
}

#[command]
fn check_models_downloaded() -> Result<bool, String> {
    use crate::models::ModelDownloader;

    let downloader = ModelDownloader::new()
        .map_err(|e| e.to_string())?;

    Ok(downloader.is_schnell_downloaded())
}

#[derive(serde::Serialize)]
struct ModelAvailability {
    id: String,
    name: String,
    is_downloaded: bool,
    has_quantized: bool,
}

/// Get availability status of all supported models
#[command]
fn get_available_models() -> Result<Vec<ModelAvailability>, String> {
    use crate::models::{ModelPaths, ModelType};

    let paths = ModelPaths::new()
        .map_err(|e| e.to_string())?;

    Ok(vec![
        ModelAvailability {
            id: "schnell".to_string(),
            name: "FLUX Schnell".to_string(),
            is_downloaded: paths.all_files_exist(),
            has_quantized: paths.has_quantized_for(ModelType::Schnell),
        },
        ModelAvailability {
            id: "dev".to_string(),
            name: "FLUX Dev".to_string(),
            is_downloaded: paths.is_dev_downloaded(),
            has_quantized: paths.has_quantized_for(ModelType::Dev),
        },
    ])
}

#[derive(serde::Serialize)]
struct ModelFileStatus {
    name: String,
    exists: bool,
    path: String,
}

#[command]
fn get_model_status() -> Result<Vec<ModelFileStatus>, String> {
    use crate::models::ModelPaths;

    let paths = ModelPaths::new()
        .map_err(|e| e.to_string())?;

    let status = paths.get_status()
        .into_iter()
        .map(|(name, exists, path)| ModelFileStatus { name, exists, path })
        .collect();

    Ok(status)
}

#[command]
fn get_hf_token() -> Result<Option<String>, String> {
    let settings = settings::AppSettings::load()
        .map_err(|e| e.to_string())?;

    Ok(settings.hf_token)
}

#[command]
fn set_hf_token(token: Option<String>) -> Result<String, String> {
    let mut settings = settings::AppSettings::load()
        .map_err(|e| e.to_string())?;

    settings.set_hf_token(token);
    settings.save()
        .map_err(|e| e.to_string())?;

    Ok("HuggingFace token saved".to_string())
}

#[command]
fn get_claude_api_key() -> Result<Option<String>, String> {
    let settings = settings::AppSettings::load()
        .map_err(|e| e.to_string())?;

    Ok(settings.claude_api_key)
}

#[command]
fn set_claude_api_key(key: Option<String>) -> Result<String, String> {
    let mut settings = settings::AppSettings::load()
        .map_err(|e| e.to_string())?;

    settings.set_claude_api_key(key);
    settings.save()
        .map_err(|e| e.to_string())?;

    Ok("Claude API key saved".to_string())
}

#[command]
fn get_fal_key() -> Result<Option<String>, String> {
    let settings = settings::AppSettings::load()
        .map_err(|e| e.to_string())?;

    Ok(settings.fal_key)
}

#[command]
fn set_fal_key(key: Option<String>) -> Result<String, String> {
    let mut settings = settings::AppSettings::load()
        .map_err(|e| e.to_string())?;

    settings.set_fal_key(key);
    settings.save()
        .map_err(|e| e.to_string())?;

    Ok("Fal.ai key saved".to_string())
}

/// Read generation metadata from a PNG image
///
/// # Arguments
/// * `image_path` - Path to the PNG image file
///
/// # Returns
/// JSON object with generation parameters if metadata is found, null otherwise
#[command]
async fn read_image_metadata(image_path: String) -> Result<Option<serde_json::Value>, String> {
    use inference::metadata::read_png_metadata_from_file;

    let path = std::path::Path::new(&image_path);
    if !path.exists() {
        return Err(format!("File not found: {}", image_path));
    }

    let metadata = read_png_metadata_from_file(path)
        .map_err(|e| format!("Failed to read metadata: {}", e))?;

    match metadata {
        Some(m) => Ok(Some(serde_json::to_value(m).map_err(|e| e.to_string())?)),
        None => Ok(None),
    }
}

// ========== Model Cache Commands ==========

/// Get current model cache statistics
#[command]
async fn get_cache_stats(
    app_state: State<'_, AppState>,
) -> Result<inference::CacheStats, String> {
    let stats = app_state.queue_processor.model_cache().get_stats().await;
    Ok(stats)
}

/// Clear all cached models and embeddings
#[command]
async fn clear_model_cache(
    app_state: State<'_, AppState>,
) -> Result<String, String> {
    app_state.queue_processor.model_cache().clear().await;
    Ok("Model cache cleared".to_string())
}

/// Get current cache configuration
#[command]
async fn get_cache_config(
    app_state: State<'_, AppState>,
) -> Result<CacheConfigResponse, String> {
    let config = app_state.queue_processor.model_cache().get_config().await;
    Ok(CacheConfigResponse {
        keep_vae_loaded: config.keep_vae_loaded,
        keep_flux_loaded: config.keep_flux_loaded,
        keep_t5_loaded: config.keep_t5_loaded,
        keep_clip_loaded: config.keep_clip_loaded,
        embedding_cache_size: config.embedding_cache_size,
        idle_timeout_secs: config.idle_timeout_secs,
    })
}

#[derive(serde::Serialize, serde::Deserialize)]
struct CacheConfigResponse {
    keep_vae_loaded: bool,
    keep_flux_loaded: bool,
    keep_t5_loaded: bool,
    keep_clip_loaded: bool,
    embedding_cache_size: usize,
    idle_timeout_secs: Option<u64>,
}

/// Update cache configuration
#[command]
async fn set_cache_config(
    app_state: State<'_, AppState>,
    keep_vae_loaded: Option<bool>,
    keep_flux_loaded: Option<bool>,
    keep_t5_loaded: Option<bool>,
    keep_clip_loaded: Option<bool>,
    embedding_cache_size: Option<usize>,
    idle_timeout_secs: Option<u64>,
) -> Result<String, String> {
    let cache = app_state.queue_processor.model_cache();
    let mut config = cache.get_config().await;

    // Update only provided fields
    if let Some(v) = keep_vae_loaded {
        config.keep_vae_loaded = v;
    }
    if let Some(v) = keep_flux_loaded {
        config.keep_flux_loaded = v;
    }
    if let Some(v) = keep_t5_loaded {
        config.keep_t5_loaded = v;
    }
    if let Some(v) = keep_clip_loaded {
        config.keep_clip_loaded = v;
    }
    if let Some(v) = embedding_cache_size {
        config.embedding_cache_size = v;
    }
    // For idle_timeout_secs, we need special handling since None means "no timeout"
    // We use 0 to mean "disable timeout"
    if let Some(v) = idle_timeout_secs {
        config.idle_timeout_secs = if v == 0 { None } else { Some(v) };
    }

    cache.set_config(config).await;
    Ok("Cache configuration updated".to_string())
}

/// Apply a cache configuration preset
#[command]
async fn set_cache_preset(
    app_state: State<'_, AppState>,
    preset: String,
) -> Result<String, String> {
    use inference::ModelCacheConfig;

    let config = match preset.as_str() {
        "default" => ModelCacheConfig::default(),
        "keep_all" => ModelCacheConfig::keep_all_loaded(),
        "memory_saver" => ModelCacheConfig::memory_saver(),
        _ => return Err(format!("Unknown preset: {}. Use 'default', 'keep_all', or 'memory_saver'", preset)),
    };

    app_state.queue_processor.model_cache().set_config(config).await;
    Ok(format!("Cache preset '{}' applied", preset))
}

// ========== Auto-Tagging Commands ==========

/// Get the current vision model (Moondream) download status
#[command]
async fn check_vision_model_status() -> vision::VisionModelStatus {
    // Use spawn_blocking to avoid blocking the main thread
    // since the HuggingFace Hub API does synchronous I/O
    tokio::task::spawn_blocking(vision::get_model_status)
        .await
        .unwrap_or_default()
}

/// Download the Moondream vision model for local tagging
#[command]
async fn download_vision_model(
    app_handle: tauri::AppHandle,
    app_state: State<'_, AppState>,
) -> Result<String, String> {
    // Check if download is already in progress
    {
        let mut in_progress = app_state.download_in_progress.lock().await;
        if *in_progress {
            return Err("Download already in progress".to_string());
        }
        *in_progress = true;
    }

    let result = vision::download_moondream(Some(&app_handle))
        .await
        .map(|_| "Vision model downloaded successfully".to_string())
        .map_err(|e| e.to_string());

    // Reset the flag
    *app_state.download_in_progress.lock().await = false;

    result
}

/// Get auto-tagging settings from the gallery database
#[command]
async fn get_auto_tag_settings(
    app_state: State<'_, AppState>,
) -> Result<vision::AutoTagSettings, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    Ok(db.get_auto_tag_settings().unwrap_or_default())
}

/// Update auto-tagging settings in the gallery database
#[command]
async fn update_auto_tag_settings(
    app_state: State<'_, AppState>,
    settings: vision::AutoTagSettings,
) -> Result<String, String> {
    let db = app_state.gallery_db.lock().await;
    let db = db.as_ref().ok_or("Database not initialized")?;

    db.set_auto_tag_settings(&settings)
        .map_err(|e| format!("Failed to save settings: {}", e))?;

    Ok("Auto-tag settings saved".to_string())
}

/// Auto-tag images using the specified backend
///
/// # Arguments
/// * `image_ids` - List of image IDs to tag
/// * `backend` - Optional backend preference ("local" or "claude"). Uses settings default if not provided.
#[command]
async fn auto_tag_images(
    app_state: State<'_, AppState>,
    image_ids: Vec<String>,
    backend: Option<String>,
) -> Result<Vec<vision::TaggingResult>, String> {
    use tracing::{info, warn};

    // Phase 1: Get settings and image paths from database, then release lock
    let (settings, image_paths, mut results, effective_backend) = {
        let db = app_state.gallery_db.lock().await;
        let db = db.as_ref().ok_or("Database not initialized")?;

        // Get settings
        let settings = db.get_auto_tag_settings().unwrap_or_default();

        // Determine backend to use
        let requested_backend = backend
            .and_then(|b| b.parse::<vision::TaggingBackend>().ok())
            .unwrap_or(settings.preferred_backend);

        let effective_backend = match requested_backend {
            vision::TaggingBackend::Local => {
                if vision::is_moondream_downloaded() {
                    Some(vision::TaggingBackend::Local)
                } else if settings.is_claude_available() {
                    warn!("Local model not available, falling back to Claude");
                    Some(vision::TaggingBackend::Claude)
                } else {
                    None
                }
            }
            vision::TaggingBackend::Claude => {
                if settings.is_claude_available() {
                    Some(vision::TaggingBackend::Claude)
                } else if vision::is_moondream_downloaded() {
                    warn!("Claude API not available, falling back to local");
                    Some(vision::TaggingBackend::Local)
                } else {
                    None
                }
            }
        };

        let effective_backend = effective_backend
            .ok_or("No tagging backend available. Download Moondream or configure Claude API key.")?;

        let mut results = Vec::with_capacity(image_ids.len());
        let mut image_paths = Vec::new();

        // Get image paths
        for id in &image_ids {
            match db.get_image_by_id(id) {
                Ok(Some(img)) => image_paths.push((id.clone(), std::path::PathBuf::from(img.file_path))),
                Ok(None) => {
                    results.push(vision::TaggingResult {
                        image_id: id.clone(),
                        tags: vec![],
                        backend: effective_backend,
                        success: false,
                        error: Some("Image not found".to_string()),
                    });
                }
                Err(e) => {
                    results.push(vision::TaggingResult {
                        image_id: id.clone(),
                        tags: vec![],
                        backend: effective_backend,
                        success: false,
                        error: Some(format!("Database error: {}", e)),
                    });
                }
            }
        }

        (settings, image_paths, results, effective_backend)
    }; // Database lock released here

    info!(
        backend = %effective_backend,
        count = image_paths.len(),
        "Starting auto-tagging"
    );

    // Phase 2: Process images (no database lock held)
    let mut tagging_results: Vec<(String, Result<Vec<vision::TagWithConfidence>, String>)> = Vec::new();

    match effective_backend {
        vision::TaggingBackend::Local => {
            // Use local Moondream model (currently stub)
            use candle_core::Device;
            let device = Device::cuda_if_available(0).unwrap_or(Device::Cpu);

            match vision::MoondreamTagger::new(device) {
                Ok(mut tagger) => {
                    for (image_id, path) in image_paths {
                        let result = tagger.extract_tags(&path)
                            .map(|mut tags| {
                                tags.retain(|t| t.confidence >= settings.min_confidence);
                                tags
                            })
                            .map_err(|e| e.to_string());
                        tagging_results.push((image_id, result));
                    }
                }
                Err(e) => {
                    // If model loading fails, mark all as failed
                    for (image_id, _) in image_paths {
                        tagging_results.push((image_id, Err(format!("Failed to load model: {}", e))));
                    }
                }
            }
        }
        vision::TaggingBackend::Claude => {
            // Use Claude Vision API
            let api_key = settings.claude_api_key.clone()
                .ok_or("Claude API key not configured")?;

            let tagger = vision::ClaudeTagger::new(api_key);

            for (image_id, path) in image_paths {
                let result = tagger.extract_tags(&path).await
                    .map(|mut tags| {
                        tags.retain(|t| t.confidence >= settings.min_confidence);
                        tags
                    })
                    .map_err(|e| e.to_string());
                tagging_results.push((image_id, result));
            }
        }
    }

    // Phase 3: Save tags to database
    {
        let db = app_state.gallery_db.lock().await;
        let db = db.as_ref().ok_or("Database not initialized")?;

        for (image_id, result) in tagging_results {
            match result {
                Ok(tags) => {
                    // Save tags to database
                    if let Err(e) = db.bulk_add_tags_with_category(&image_id, &tags) {
                        warn!(error = %e, "Failed to save tags to database");
                    }

                    results.push(vision::TaggingResult {
                        image_id,
                        tags,
                        backend: effective_backend,
                        success: true,
                        error: None,
                    });
                }
                Err(e) => {
                    results.push(vision::TaggingResult {
                        image_id,
                        tags: vec![],
                        backend: effective_backend,
                        success: false,
                        error: Some(e),
                    });
                }
            }
        }
    }

    info!(
        success_count = results.iter().filter(|r| r.success).count(),
        total = results.len(),
        "Auto-tagging complete"
    );

    Ok(results)
}

// ========== System Stats Commands ==========

#[derive(serde::Serialize)]
struct SystemStats {
    /// CPU usage as percentage (0-100)
    cpu_usage: f32,
    /// Memory used in bytes
    memory_used: u64,
    /// Total memory in bytes
    memory_total: u64,
    /// Memory usage as percentage (0-100)
    memory_percent: f32,
    /// GPU memory used in bytes (if available)
    gpu_memory_used: Option<u64>,
    /// GPU memory total in bytes (if available)
    gpu_memory_total: Option<u64>,
    /// GPU usage percentage (if available)
    gpu_usage_percent: Option<f32>,
    /// GPU name (if available)
    gpu_name: Option<String>,
    /// Whether a generation is currently running
    is_generating: bool,
}

/// Get current system resource usage (CPU, RAM, GPU)
#[command]
async fn get_system_stats(
    app_state: State<'_, AppState>,
) -> Result<SystemStats, String> {
    use sysinfo::System;

    let mut sys = System::new();
    sys.refresh_cpu_all();
    sys.refresh_memory();

    // Wait a bit for CPU readings to stabilize
    tokio::time::sleep(tokio::time::Duration::from_millis(100)).await;
    sys.refresh_cpu_all();

    // Calculate average CPU usage across all cores
    let cpu_usage: f32 = sys.cpus().iter().map(|cpu| cpu.cpu_usage()).sum::<f32>()
        / sys.cpus().len().max(1) as f32;

    let memory_used = sys.used_memory();
    let memory_total = sys.total_memory();
    let memory_percent = if memory_total > 0 {
        (memory_used as f64 / memory_total as f64 * 100.0) as f32
    } else {
        0.0
    };

    // Check if generating
    let is_generating = {
        let jobs = app_state.queue_manager.get_jobs().await;
        jobs.iter().any(|j| j.status == queue::JobStatus::Running)
    };

    // Try to get GPU stats via CUDA (Linux) or nvml
    let (gpu_memory_used, gpu_memory_total, gpu_usage_percent, gpu_name) = get_gpu_stats();

    Ok(SystemStats {
        cpu_usage,
        memory_used,
        memory_total,
        memory_percent,
        gpu_memory_used,
        gpu_memory_total,
        gpu_usage_percent,
        gpu_name,
        is_generating,
    })
}

/// Get GPU stats using nvidia-smi (cross-platform fallback)
fn get_gpu_stats() -> (Option<u64>, Option<u64>, Option<f32>, Option<String>) {
    // Try to run nvidia-smi to get GPU stats
    let output = std::process::Command::new("nvidia-smi")
        .args([
            "--query-gpu=memory.used,memory.total,utilization.gpu,name",
            "--format=csv,noheader,nounits",
        ])
        .output();

    match output {
        Ok(output) if output.status.success() => {
            let stdout = String::from_utf8_lossy(&output.stdout);
            let line = stdout.lines().next().unwrap_or("");
            let parts: Vec<&str> = line.split(',').map(|s| s.trim()).collect();

            if parts.len() >= 4 {
                let mem_used = parts[0].parse::<u64>().ok().map(|v| v * 1024 * 1024); // MiB to bytes
                let mem_total = parts[1].parse::<u64>().ok().map(|v| v * 1024 * 1024);
                let gpu_util = parts[2].parse::<f32>().ok();
                let gpu_name = Some(parts[3].to_string());

                return (mem_used, mem_total, gpu_util, gpu_name);
            }
        }
        _ => {}
    }

    (None, None, None, None)
}

/// Analyze an image using Claude and generate a prompt to recreate it
///
/// # Arguments
/// * `image_data` - Base64-encoded image data (can include data URL prefix)
/// * `media_type` - Optional MIME type. If not provided, will be inferred from data URL.
#[command]
async fn analyze_image_for_prompt(
    image_data: String,
    media_type: Option<String>,
) -> Result<String, String> {
    // Load Claude API key from settings
    let settings = settings::AppSettings::load()
        .map_err(|e| e.to_string())?;

    let api_key = settings.claude_api_key
        .ok_or_else(|| "Claude API key not configured. Please set it in Settings.".to_string())?;

    // Parse image data - handle both raw base64 and data URL formats
    let (base64_data, mime_type) = if image_data.starts_with("data:") {
        // Parse data URL: data:image/png;base64,xxxxx
        let parts: Vec<&str> = image_data.splitn(2, ',').collect();
        if parts.len() != 2 {
            return Err("Invalid data URL format".to_string());
        }

        // Extract MIME type from header
        let header = parts[0];
        let inferred_mime = header
            .strip_prefix("data:")
            .and_then(|s| s.split(';').next())
            .unwrap_or("image/png")
            .to_string();

        (parts[1].to_string(), media_type.unwrap_or(inferred_mime))
    } else {
        // Raw base64 - use provided media type or default
        (image_data, media_type.unwrap_or_else(|| "image/png".to_string()))
    };

    // Call Claude API to analyze the image
    claude::analyze_image_for_prompt(&api_key, &base64_data, &mime_type)
        .await
        .map_err(|e| e.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Initialize logging (defaults to info level, use RUST_LOG to override)
    init_logging("info");

    let gallery_db = Arc::new(Mutex::new(None));
    let queue_manager = Arc::new(queue::QueueManager::new(1)); // Max 1 concurrent for now

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .setup(move |app| {
            // Get app handle
            let app_handle = app.handle().clone();

            // Create processor with app handle (needs its own clone)
            let queue_processor = Arc::new(
                QueueProcessor::new(
                    queue_manager.clone(),
                    gallery_db.clone(),
                    app_handle.clone(),
                ).expect("Failed to create queue processor")
            );

            // Store in managed state
            app.manage(AppState {
                gallery_db: gallery_db.clone(),
                queue_manager: queue_manager.clone(),
                queue_processor: queue_processor.clone(),
                app_handle,
                download_in_progress: Arc::new(Mutex::new(false)),
            });

            // Start processor
            tauri::async_runtime::spawn(async move {
                queue_processor.start().await;
            });

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            health_check,
            init_database,
            generate_image,
            get_gallery_images,
            search_gallery_images,
            toggle_favorite,
            add_image_tag,
            remove_image_tag,
            delete_gallery_image,
            add_to_queue,
            get_queue_jobs,
            get_queue_job,
            cancel_queue_job,
            clear_completed_jobs,
            // Folder commands
            create_folder,
            update_folder,
            delete_folder,
            move_folder,
            get_folder_tree,
            add_images_to_folder,
            remove_images_from_folder,
            get_folder_images,
            get_uncategorized_images,
            // Enhanced tag commands
            get_all_tags,
            update_tag,
            bulk_add_tag,
            bulk_remove_tag,
            // Model download commands
            download_flux_schnell,
            download_flux_dev,
            check_models_downloaded,
            get_model_status,
            get_available_models,
            // Settings commands
            get_hf_token,
            set_hf_token,
            get_claude_api_key,
            set_claude_api_key,
            get_fal_key,
            set_fal_key,
            // Image analysis
            analyze_image_for_prompt,
            read_image_metadata,
            // Model cache commands
            get_cache_stats,
            clear_model_cache,
            get_cache_config,
            set_cache_config,
            set_cache_preset,
            // Auto-tagging commands
            check_vision_model_status,
            download_vision_model,
            get_auto_tag_settings,
            update_auto_tag_settings,
            auto_tag_images,
            // System stats
            get_system_stats,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
